### ISSUE TITLE
Windows `grunt dev` pug-lint-vue Error

### ISSUE THREAD

**Issue by CrazedCoding** [okTurtles/group-income#1007]
### Problem

I followed the "Getting Started" instructions on my Windows 10 machine, and ended up getting the following error when attempting to run `grunt dev`:

![image](https://user-images.githubusercontent.com/18431780/97607386-47f04300-19e7-11eb-8fe9-883170d9b804.png)

It seems to have something to do with the behavior of the `grunt-puglint` feature.

### Solution

First, do research into OS-dependent behavior of `pug-lint-vue`. Once the difference is understood, then suggest a more detailed solution.

**Comment by SebinSong** [comment]
I get the same errors while running `grunt dev` and manually removed those blank lines for now.

**Comment by snowteamer** [comment]
Although I am also using Windows, currently I am not affected by this issue, perhaps because I have set up Git and my editor to only use `\n`.

So I guess it has to do with `pug-lint-vue` somehow incorrectly handling `\r\n`.

In particular, [this regular expression](https://github.com/sourceboat/pug-lint-vue/blob/416ad8e4ba551f008abcf1b459ace7bb8fd1f226/lib/linter.js#L50) in `pug-lint-vue`'s source code looks suspicious:
```js
        // Remove first and last line-break, as these contain the opening /
        // closing <template> tag expressions and should not count as empty
        // lines.
        const text = template.match(/^[\r\n|\n|\r]?([\s\S]*?)[\r\n|\n|\r]?$/)[1]
        ...
```
Therefore I considered opening an issue in `pug-lint-vue`, but the repo has beed archived by its owner and is now read-only, so no more patchs will be accepted there.

**Comment by snowteamer** [comment]
Is this issue still relevant for someone?

Otherwise, for example if configuring one's editor to use `\n` as line separator was enough to make any problem disappear, then I would suggest closing it, since an actual solution might be rather costly:

- Either fork `pug-lint-vue` to patch it
- Or add a step to our already complex grunt file to dynamically patch the `pug-lint-vue` source code before loading it

**Comment by taoeffect** [comment]
Well, forking `pug-lint-vue` isn't difficult. If anyone wants to work on this you can submit a PR to our fork of it here: https://github.com/okTurtles/pug-lint-vue
