### ISSUE TITLE
Zero is not negative / People should be able to pledge $0

### ISSUE THREAD

**Issue by CrazedCoding** [okTurtles/group-income#1017]
### Problem

According to our leading zoologist of thought (mathematicians), zero is not negative:

![image](https://user-images.githubusercontent.com/18431780/99720216-6fcd4680-2a7b-11eb-8211-b6c7ab0bfbd1.png)

### Solution

![fixit](https://user-images.githubusercontent.com/18431780/99720692-19acd300-2a7c-11eb-8a8f-28d47d3167b8.gif)

**Comment by snowteamer** [comment]
That error occurs in IncomeDetails.vue when the input amount gets passed to `mincomePositive()` which is defined in currencies.js.

Despite its name, `mincomePositive()` currently only allows *strictly* positive amounts, i.e. greater than zero:

```js
export function mincomePositive (value: string): boolean {
  return parseFloat(commaToDots(value)) > 0
}
```
So in theory it would be enough to replace the `>` operator by `>=` to make it work as its name suggests, while also allowing users to pledge zero.

However, this function is also used in other components, namely `GroupCreationModal.vue` and `Mincome.vue`,
which rely on its current behavior to disallow specifying zero as the group mincome.

Therefore I think a distinct validator is needed here, especially since the amount users want to pledge is not really a mincome but a contribution towards one.
