### ISSUE TITLE
Invite link sharing doesn't work on mobile [$100 bounty]

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1021]
### Problem

Tapping on the invite link on mobile brings up the sharing feature, and when I choose email, it creates an empty email without the link:

![a](https://user-images.githubusercontent.com/138706/100532808-e2dc6880-31b1-11eb-84c6-389257f96af6.jpg)

### Solution

Fix!

### Bounty

$100 bounty for a clean solution to this (paid in cryptocurrency).

**Comment by taoeffect** [comment]
Adding a $100 bounty for closing this issue for non-contractors (meaning, if you don't have a development contract with okTurtles, and you'd like to close this issue, you can work on it, and if we accept your PR, you'll receive the bounty).

Anyone else can add to the bounty too if they'd like by following these simple steps:

1. Donate the amount you'd like to dedicate to this issue [to the okTurtles Foundation](https://okturtles.org/donate/).
2. Make a comment here (or privately to us via Gitter or Slack) the same day letting us know you'd like your donation to be used for a bounty to close an issue, and which issue that is.

**Comment by snowteamer** [comment]
Default invite link from the Group Settings modal also doesn't show up on mobile either:

![image](https://user-images.githubusercontent.com/64228468/132070559-e796dd27-571d-4bda-a888-e0fd136e718f.png)

Furthermore, the Copy Link option from the associated popup menu doesn't appear to actually copy the link to the clipboard.

**Comment by abdulazizali77** [comment]
hi @taoeffect 
currently there seems to be four codepaths for the sharing

1. not mobile and `navigator.share` is defined
2. not mobile and `navigator.share` is not defined
3. mobile and `navigator.share` is defined. 
4. mobile and `navigator.share` is not defined, 

For (1) and (2) `c-invite-link-wrapper` and the invite link url are hidden while `c-invite-link-button-mobile` is shown. Sharing is done in `activateWebShare` function defined in `InvitationsTable.vue`
For (3) and (4) `c-invite-link-wrapper` and the invite link url are shown while `c-invite-link-button-mobile` is hidden. Sharing is done in `copyToClipboard` function defined in `LinkToCopy.vue`
For cases (2) (4 ) where `navigator.share` is not defined, the `activateWebShare` and `copyToClipboard` respectively do manual handling and `copy` command.

Right now in your report, we dont know what browser or device you were using, but looking at the code, its weird that it would follow the (2) codepath unless your mobile is wider than normal (768px ? ).
For me i couldnt really reproduce the issue on mobile (it all followed (4) codepath), because non of the browsers on my mobile supported `navigator.share` (https://caniuse.com/?search=navigator.share). It wasnt hard to reproduce (1) on desktop with simulator yet unable to verify whether this was the error you encountered. The previous `textToCopy` in `LinkToCopy` was the only bug i sort of found (in the (1) codepath) while `activateWebShare` appears fine. The most common behaviour i see from my testing is that when the shared link is invalid url/empty the web sharing API mechanism would just complain, and wouldnt even present the available share options, so thats another weird thing if your device actually allowed invalid urls.
Anyways could you tell us the device browser you used and or try the PR fix? 

for @snowteamer 's issue, we can definitely redesign to show the `c-invite-link` for mobile but how do you propose to do it? 
Also the first question is should the two copy approaches be consolidated, which highly likely would mean `activateWebShare` should be removed because `copyToClipboard` is modular and is used in other views 
For a redesign Im thinking the `tbody tr` should just `flex-wrap: wrap` and the `td` widths should be 100%
~it should be all divs like so, and the divs will be laid out as columns in non mobile and all rows when mobile~

**Comment by taoeffect** [comment]
@abdulazizali77 Hey Abdul - thanks so much for the PR! Today I don't have much time at the computer but later tonight or tomorrow I'll have a look at it and try it out. Will also get back to you about your questions. /cc @leihla regarding design question

You're welcome to [join our Slack](https://join.slack.com/t/okturtles/shared_invite/zt-10jmpfgxj-tXQ1MKW7t8qqdyY6fB7uyQ) btw if you'd like. :)

**Comment by taoeffect** [comment]
Closed via @abdulazizali77's PR, thanks for sending this in! Please end me a DM on Slack for payment info.

And if you think some refactoring is in order, you're welcome to send us either a proposal or a PR with what you have in mind and we'll review!

I know the Contributing guidelines say to send the PR from a branch in your fork - but please try to push your branch to our repo instead - I'm curious if it will allow you to, as then the Travis tests should get triggered. If it works for any future PRs you send in, I'll update the contributing guidelines to make note of this.

**Comment by abdulazizali77** [comment]
> And if you think some refactoring is in order, you're welcome to send us either a proposal or a PR with what you have in mind and we'll review!

will do! ill push the branch to upstream next time
