### ISSUE TITLE
Offline user data not fully updated on logout

### ISSUE THREAD

**Issue by snowteamer** [okTurtles/group-income#1102]
### Problem

I noticed that `sbp('gi.db/settings/save', username)` was apparently not called on logout, resulting in the `loggedIn` field not being reset to `false` in offline data.

### Solution

If this offline field should be set back to `false` on user logout, then find a suitable place to call `gi.db/settings/save` with the relevant username and updated data. Maybe in the logout action handler: https://github.com/okTurtles/group-income-simple/blob/b4b71a0c97c050d02c07db015ca7a0a60652e526/frontend/model/state.js#L712

For example (provided only `loggedIn` has to be updated here):
```js
const userSettings = await sbp('gi.db/settings/load', username)
await sbp('gi.db/settings/save', username, { ...userSettings, loggedIn: false })
```
Double-check other fields do not become out of sync too, unless they are explicitly allowed to.
Maybe add a Cypress test to ensure offline user data is valid after logout.

Providing access to `sbp` in the browser dev console while in development mode might help in investigating this.

**Comment by taoeffect** [comment]
@snowteamer So I'm trying to wrap my head around what it is that you're pointing to, because `sbp('gi.db/settings/save', username` is called on logout:

```js
  async logout (
    { dispatch, commit, state }: {dispatch: Function, commit: Function, state: Object}
  ) {
    debouncedSave.clear()
    await dispatch('saveSettings') // <----------------- RIGHT HERE
    await sbp('gi.db/settings/save', SETTING_CURRENT_USER, null)
```

`await dispatch('saveSettings')` is called, which results in a call to the following:

```js
  // persisting the state
  async saveSettings (
    { state }: {state: Object}
  ) {
    if (state.loggedIn) {
      // TODO: encrypt this
      await sbp('gi.db/settings/save', state.loggedIn.username, state)
    }
  },
```

Up to this point it saves the settings, but you are right that so far it doesn't reset `state.loggedIn` — Yet.

Back in `async logout`, we have further down:

```js
  async logout (
    { dispatch, commit, state }: {dispatch: Function, commit: Function, state: Object}
  ) {
    debouncedSave.clear()
    await dispatch('saveSettings')
    await sbp('gi.db/settings/save', SETTING_CURRENT_USER, null)
    for (const contractID in state.contracts) {
      commit('removeContract', contractID)
    }
    commit('logout') // <-------------- THIS
```

If we look at the mutation for `'logout'`, we see this:

```js
  logout (state) {
    state.loggedIn = false
    state.currentGroupId = null
  },
```

So `state.loggedIn` does appear to get set to `false`...

I've removed the `Kind:Bug` label from this and am leaving this issue open as a discussion so that we can see whether or not you're noticing some real bug, but having to do with something else. Let me know you're thoughts, if you think I'm mistaken, etc.

**Comment by snowteamer** [comment]
@taoeffect Although the `logout` mutation handler does set `state.loggedIn` to `false` as you described, it only does it in-memory, which is not enough to also persist the change to offline storage.

By the way, from the above code the same thing seem to happen with `state.currentGroupId` and `state.contracts`.

Agreed, this is somewhat confusing behavior, which can be explained by remembering that mutating a plain object after it has already been serialized and persisted will not update the persisted data.

**Comment by taoeffect** [comment]
@snowteamer so I get that it won't update the persisted data, but can you explain how that results in a problem? If the state is restored, it's only done so when we're logged in, and then I believe it's updated too.

**Comment by snowteamer** [comment]
@greg It might not cause any immediate problem with the app, but it still results in a non-obvious data inconsistency.
Regarding `state.currentGroupId` and `state.contracts`, they could be retrieved after user logout just by inspecting the local offline storage. Keeping `state.contracts` stored offline also takes up a bit of valuable space when subscribed to many contracts. 

So unless this data is necessary e.g. for the app to work offline, I'm not seeing any benefit for not cleaning it up before logging out.

**Comment by taoeffect** [comment]
> Keeping `state.contracts` stored offline also takes up a bit of valuable space when subscribed to many contracts.

That's a fairly small object to store... so I'm not sure I buy that... It's also a very important piece of data to store persistently, because it tells us where we left off before when we log in again. We need to know that information so that we can request the right number of events between where we left off and the latest events.

The reason we have this problem/solution format for issues is so that a clear problem can be identified. I'm still not seeing a clear problem.

**Comment by snowteamer** [comment]
@greg Ok, closing this one then. No worries! :)
