### ISSUE TITLE
Pubsub breaks with computer sleep... [$150 bounty]

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1127]
### Problem

Context: I had the deployed site open in a pinned tab in the background (in other words, the pinned tab was not selected, I was doing other browsing, I put the computer to sleep, left it there for a few minutes, *stuff happened in the group while I was away*, woke the computer, went back to browsing, and then clicked on the pinned tab to see if saw any of the changes - in this case someone had joined the group).

These repeated errors appeared in Firefox console:

![sleep issue](https://user-images.githubusercontent.com/138706/145073448-c3f2d142-9344-4c2a-9bd6-07368691b90c.jpg)

It's not clear to me what the issue is because the code that's linked to is related to error logging... and that could mean an error happened in the pubsub code *and* in the logging code:

```js
function captureLogsStart(userLogged) {
  isCapturing = true;
  username = userLogged;
  clearLogs();
  verifyLogsConfig();
  appLogsFilter = sbp_default("state/vuex/state").appLogsFilter || [];
  sbp_default("okTurtles.events/on", SET_APP_LOGS_FILTER, (filter) => {
    appLogsFilter = filter;
  });
  if (!isConsoleOveridden) {
    isConsoleOveridden = true;
    window.console = new Proxy(window.console, {
      get: (obj, type) => (...args) => {
        if (appLogsFilter.includes(type)) {
          obj[type](...args);                      // <---- console says error in 'get' on this line
          if (isCapturing) {
            captureLog(type, ...args);
            verifyLogsSize();
          }
        }
      }
    });
```

### Solution

Find the problem in both logging and pubsub and fix.

### Bounty

Issue is open to contractors or non-contractors. Non-contractors can get paid via bounty. We're posting a bounty of $150 for a clean solution to this issue.

**Comment by snowteamer** [comment]
At first guess these errors are timeouts arising from repeated reconnection attempts, while the server has already closed the connection because the client was irresponsive while the computer was in sleep mode.

I think the warning about Console API deactivation is simply there to remind us that the Console API has indeed been proxied, which means console calls might no longer result in their default behavior. There were actually more messages displayed in development mode.

Is there still a synchronization issue after a shorter sleep, short enough so that the client is still able to successfully reconnect?
In that scenario, all the waiting socket packets should now be transmitted and the view should be updated accordingly.

**Comment by taoeffect** [comment]
> I think the warning about Console API deactivation is simply there to remind us that the Console API has indeed been proxied, which means console calls might no longer result in their default behavior. There were actually more messages displayed in development mode.

Yes, however the error (not the warning) comes from that console logging code that I shared above... so not sure what's up with that.

> Is there still a synchronization issue after a shorter sleep, short enough so that the client is still able to successfully reconnect?

How short of a sleep? There's definitely not an issue after a few seconds of sleep, but I'm guessing that's too short to matter.

**Comment by snowteamer** [comment]
In a first time it takes between 30s and 1min for the server to notice that a given client is sleeping or irresponsive.

Did you immediately come back to the Group Income tab upon waking up the computer?

Because once awake again, the disconnected client should attempt to reconnect up to 10 times, using increasing and slightly randomized delays between attempts, from 500ms to 60s following the current client options.

**Comment by taoeffect** [comment]
> Did you immediately come back to the Group Income tab upon waking up the computer?

No I don't think so. I can do some additional testing later.

Regarding the displayed error in the screenshot - it's a "pubsub error", but it seems to be pointing to our code in `captureLogs.js`, again:

```js
    window.console = new Proxy(window.console, {
      get: (obj, type) => (...args) => {
        if (appLogsFilter.includes(type)) {
          obj[type](...args) /// <----------------HERE
          if (isCapturing) {
            captureLog(type, ...args)
            verifyLogsSize()
          }
        }
      }
    })
```

My guess about this is that it's possible that `obj` is undefined there, because it refers to an original `window.console` object that has become deallocated...? Maybe?
