### ISSUE TITLE
cookies HTTPS only

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#12]
``` js
  server.auth.strategy('cookie_strategy', 'cookie', {
    password: 'abcdef',
    cookie: 'group-income-simple',
    ttl: 2592000000, // 1 month
    isSecure: false // HTTP allowed
  })
```

What's the reason `isSecure` is set to `false` there?

**Comment by liamsi** [comment]
I guess the only reason for the `isSecure: false // HTTP allowed` line is to make local development as easy as possible. Otherwise (if `isSecure: true`\- which is the default) one would need to generate a valid (e.g. self-signed) certificate for `localhost` (using openssl), which I think is a good idea. 

Do the following steps make sense (?):
- [ ] include description on how-to create self-signed certificate using `openssl` (or link to sth like [this](https://devcenter.heroku.com/articles/ssl-certificate-self))
- [ ] [start Hapi using tls](http://hapijs.com/api/0.15.1#tls) with the above [generated key/cert](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener)
- [ ] make the usage optional on localhost with an env/global flag (default) for convenience (?)

Not sure about the last step: it's only there to make the barriers to run it locally as low as possible.

**Comment by taoeffect** [comment]
Ah I see. Well if that's the case it's better to generate the self-signed cert ourselves (less hassle for users/devs, plus keeps the README clean).

I already wrote code to do this in DNSChain, so that can just be carried over here:
- https://github.com/okTurtles/dnschain/blob/master/src/lib/https.coffee#L51-L75
- https://github.com/okTurtles/dnschain/blob/master/src/lib/pem.coffee#L31-L42
- https://github.com/okTurtles/dnschain/blob/master/docs/How-do-I-run-my-own.md#verify-the-ssltls-key-and-certificate-fingerprint

So no to manual generation, yes to starting Hapi with the autogen'd one, and we can put off deciding whether or not to make it optional for now. :smile:
