### ISSUE TITLE
Remove checkIfJoinedGeneralChannel from frequently used support commands in Cypress

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1215]
### Problem

The Cypress tests are now a bit slower because of how much we're testing.

The Chat PR (#1143) added `checkIfJoinedGeneralChannel` to several frequently used support commands, including `giAcceptGroupInvite` and `giCreateGroup`.

### Solution

`checkIfJoinedGeneralChannel` should be removed from `giAcceptGroupInvite` and `giCreateGroup`, and only done a couple of times in `group-chat.spec.js`

**Comment by Silver-IT** [comment]
Actually, it is not only for `Group Chat` page. To join `General` chatroom is one of the steps to join a group.
Can you please confirm once again to remove it for other test scenarios instead of `group-chat.spec.js`?
I am asking this because I don't think we should remove it...

**Comment by taoeffect** [comment]
@Silver-IT Feel free to add `checkIfJoinedGeneralChannel` outside of `giCreateGroup` somewhere where you feel it's necessary. We do want to test certain scenarios at least once. My concern is that we don't unnecessarily test multiple times.

For example, if we create a group once and call `checkIfJoinedGeneralChannel`, that is fine. There's no need to call it each time we create a group though.

**Comment by Silver-IT** [comment]
As it shows by it's name, it's only for checking if he joined `General` chatroom.
There is no additional actions except joining group. Even though, it seems like it does something more, but actually it doesn't make any additional actions and the process is necessary to wait until he joined the group **COMPLETELY**.
I think even though we remove that process, we need to wait until he finishes to join `General` chatroom. Meaning no different in runtime. Then, why should we remove it?

**Comment by taoeffect** [comment]
I'm not sure but this might have been fixed in #1227, please double-check if there are any other places I missed.

**Comment by Silver-IT** [comment]
Actually, I don't think we should remove `checkIfJoinedGeneralChannel` function.
The reason is because
- It makes Cypress to wait until `General` chatroom contract is completely synchronized after user joins a group, so it's necessary step actually.
- It doesn't make any additional actions except redirecting to the `Group Chat` page. Even though it does any additional actions, it must be for the `General` chatroom to be completely synchronized.
- Now, we are using this function only when `bypressUI` is `false` and we don't normally call `giCreateGroup` and `giAcceptGroupInvite` with falsy `byPressUI` in the test scenario. So this function is not being called much.
