### ISSUE TITLE
Implement button to clear / archive proposals

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1233]
### Problem

Currently, proposals that have passed just stack up on top of one another.

### Solution

Once @leihla designs method to clear/archive passed proposals, please implement it.

**Comment by leihla** [comment]
This is a duplicate of the issue #924 

As discussed in our call, there is no need for a clear proposals button because:

- Only open proposals should appear the dashboard widget
- Once a proposal was approved or rejected, a notification should appear for all users in the notification center
- Closed proposals should be moved to the "See all proposals" in the dashboard widget

@taoeffect please let me know if you agree with this and create a ticket for implementation
