### ISSUE TITLE
Conflicting strings (French)

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1261]
### Problem

In merging @snowteamer's latest changes into my PR (#1250), the following string conflicts in `french.strings` were detected:

```
<<<<<<< HEAD
"Loading events for '{contract}' from server..." = "Loading events for '{contract}' from server...";
=======
"Loading events from server..." = "Synchronisation avec le serveur...";
>>>>>>> master
```

I was forced to remove the translation as it no longer applies.

### Solution

Either comment on my PR with the correct translation for the new string, or fix after my PR is merged.

The new string is the one at the top (`"Loading events for '{contract}' from server..."`)

EDIT: so this string (for UX reasons) has been changed completely to simply: `Loading events from server...`

**Comment by snowteamer** [comment]
A simple solution would be to just use a pair of parens to append the contract's display name to the existing translation:
- `"Synchronisation avec le serveur... ({contract})";`

Other possibilities I've considered:
-  `"Synchronisation des données avec le serveur... ({contract})";`

Translations containing the word "contrat" (for contract) - these might better be avoided since it's a somewhat technical term in this context:
- `"Synchronisation avec le serveur... (contrat :  {contract})";`
- `"Synchronisation du contrat  « {contract} »";`
- `"Synchronisation du contrat  « {contract} » avec le serveur";`

Also please note that since the displayed contract type or name will be a JavaScript string with no translation, it will likely look like debugging output from a French-speaking user's viewpoint.

**Comment by taoeffect** [comment]
Sure, I do like the first one, `"Loading events from server... ({contract})"` it works for English too

**Comment by taoeffect** [comment]
@pieer Per the call, I edited this issue to note that this string (for UX reasons) has been changed completely to simply: `Loading events from server...`

**Comment by pieer** [comment]
I think that's the reason:
// we can't actually show in the global banner what contract is syncing because doing
// so would involve having to repeatedly call the message() function, and if there
// were other danger banners that needed to take precedence they would get covered

So I guess we can close this issue?

**Comment by taoeffect** [comment]
Yep! Closed. Also, check out @SGrondin's latest `strings` binary, he's greatly improved it, and it fixed that issue you ran into. 😄 

https://github.com/okTurtles/strings/releases/tag/v1.3.1
