### ISSUE TITLE
DOMException: Failed to execute `setItem` on `Storage` [$50 bounty]

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1273]
### Problem

I am not sure whenever I've seen this error before.
But now, I have this error when I scroll up the messages in `Group Chat` page and try to log many events inside localStorage in a short period of time.
The expression `in a short period of time` is just my guess because we don't get this error when I scroll up slowly and give app the enough time to log and do something I don't know.
However, we actually get this error when I scroll up very quickly and tries to load several messages very soon.
![image](https://user-images.githubusercontent.com/57976479/168495238-493d6f72-8b6b-4c6a-8e7e-c84e9c6325e3.png)
Also when I refresh the page, I don't get this error too. So I guess this is not the problem sth like `Out of memory` or `Limit on memory usage`. And I used the expression `in a short period of time`.

### Solution

First things first, need to debug in `captureLogs.js`.
Not sure but need to log events synchronously.

EDIT by @taoeffect: I recommend [@snowteamer's solution](https://github.com/okTurtles/group-income/issues/1273#issuecomment-1133240119): storing the events in an in-memory array, and periodically serializing that array as the value of a single localstorage key.

### Bounty

$50 bounty for a clean solution to this (paid in cryptocurrency).

**Comment by taoeffect** [comment]
Is this happening in a special branch that you're working on or on `master`? If it's a special branch then please self-assign as only you can debug.

Some tips for debugging this:

- have a look in that tab at what you see in the “Storage” tab for localstorage - filter for `giConsole` and see what shows up, and also see what's there without the `giConsole` filter. The `captureLogs.js` code should limit the amount of `giConsole/{username}` messages to `ENTRIES_LIMIT`, which is set to 5000 currently. Verify that is working:
    
     <img width="773" alt="Screen Shot 2022-05-15 at 2 53 40 PM" src="https://user-images.githubusercontent.com/138706/168495577-f54d83fc-4e95-4676-ae99-e4bb7bf1d936.png">

- Remove the `giConsole` filter and see what other items are being stored in localstorage to see if something else is clogging it

**Comment by taoeffect** [comment]
Another possible "solution" would be @snowteamer's suggestion of simply storing the log lines in-memory.

Pros:

- It might make the app slightly faster, especially if debug logging is enabled

Cons:

- It could prevent the logs from being as useful. For example, the following situation could occur: 1 error triggers several other errors. The user refreshes the page, wiping out the logs, and we are sent only the followup errors, but not the original error that triggered them

**Comment by snowteamer** [comment]
In principe it should be possible to preserve the logs across page refreshs, by flushing the log array contents to local storage upon certain events:
- periodically, e.g. once every 5 minutes or when reaching a certain number of elements. This would allow us to use a fixed-length array.
- when a runtime error occurs. We would have to make sure the log saving code gets called whenever such an error is about to be thrown. Maybe by patching our custom error constructors, so that calling e.g. `new GIRuntimeError()` would seemlessly save the logs as a side-effect.
- when the page is about to be refreshed. The `onbeforeunload` event might be usable to do that, although it has some caveats regarding page caching that would need to be researched first.

**Comment by taoeffect** [comment]
I think @snowteamer's solution is the correct one, but as a hack I was just forced to employ, I reduced the limit by modifying the configuration like so:

```
// Configuration
const ENTRIES_LIMIT = 2000
const ENTRIES_MARKER_NTH = 500
```

~~And that seems to have fixed it.~~ **(EDIT: NO! The `ENTRIES_LIMIT` isn't the problem! See next comment for more info.)** However, I agree with @snowteamer - his solution is far better. But we also need to keep this limit in mind too.

**Comment by taoeffect** [comment]
Actually - it turns out that lowering the `ENTRIES_LIMIT` didn't fix it! 😱 

I don't think it has anything to do with that!

My best guess is that this is a browser bug that's caused by localStorage being written to too fast, because I checked `localStorage.length` and it is a low value - so this shouldn't have caused the problem.

I think the only real solution then is to modify the code to implement @snowteamer's suggest - and have it periodically save the entire log array as the value, instead of having 1-entry per log line.

**Comment by taoeffect** [comment]
Added a bounty to this issue.
