### ISSUE TITLE
Debug logging should show up if the user enables debug logging

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1276]
### Problem

Currently the SBP debug logging check in `main.js` looks like this:

```js
  const debugParam = new URLSearchParams(window.location.search).get('debug')
  if (process.env.NODE_ENV !== 'production' || debugParam === 'true') {
```

It doesn't enable debug logging of SBP calls if the user enabled debug logging in their user settings.

### Solution

This is tricky as there are a few considerations.

- One might be tempted to somehow integrate with `sbp('state/vuex/state').appLogsFilter`, but that isn't available at that point (only upon login)
- It's tempting to simply remove the `if (process.env.NODE_ENV !== 'production' || debugParam === 'true') {` check, as that would then display debug logging upon login if the `appLogsFilter` has it enabled. However, users might accidentally leave this on and forget to turn if off, so perhaps the `debugParam` is the way to go (and we should entirely remove the checkbox for enabling debug logging from the UI). Think about this.

**Comment by snowteamer** [comment]
> perhaps the debugParam is the way to go (and we should entirely remove the checkbox for enabling debug logging from the UI)

Without that checkbox, unless we enable debug logging by default, how would we know what happened when a user encounters a bug in production?
Would we have to ask them to append `?debug=true` in their address bar, reload the page, and try reproducing the offending steps? This might not always be easy or even feasible with real users and groups.

So as I perceive it, the debugParam is rather a feature for developers and GI server admins, especially since not every user is going to know about this ` "trick".
> This is tricky as there are a few considerations.

A solution I'm thinking about would be based on using different `appsLogsFilter` default values according to whether `debugParam` was set.
