### ISSUE TITLE
Finish designs for new proposals look & create issue for implementation

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1288]
### Problem

The designs for the new proposals dashboard widget is missing some things:

1. The "Vote" button should be restored to the 2 buttons (yes/no)
2. I don't remember what we agreed upon @leihla as far as how proposals are archived - whether manually with a button, or after a timeout, or both, but that should be documented clearer, any designs for it designed
3. Update the Dashboard Figma page with just the new proposals design (remove all old designs to avoid confusion)
4. Finally, create an issue for implementing the new designs and assign it to @pieer 

### Solution

Do the needed steps to finish the designs for the new proposals designs, and create and assign an issue to @pieer to implement, marking it as high prioroity.

**Comment by leihla** [comment]
Proposals dashboard widget has changed the way to show proposals.

### Problems with previous solution:

- Focus was on the user that was proposing instead of the proposal itself
- Proposals could be grouped which made it harder to implement and to vote independently on different proposals created at the same time (for instance, adding multiple members on a same proposal)
- It didn't show the expiration date of a proposal, so there was no sense of urgency in voting
<img width="765" alt="Screenshot 2022-06-14 at 11 53 26" src="https://user-images.githubusercontent.com/158178/173561351-8181dde8-8801-4aff-b7f9-916f21bbe0d6.png">

---

### New design solution:

- Focus on the proposal: the title makes it clear what is being proposed. Instead of "Margarida is proposing" it shows "Add Felix Kubin to the group" 
- Show proposal type icon with small avatar attached to it - makes it clear what type of proposal are you voting on while still showing who is proposing it
- Add Proposal Expiration date

<img width="790" alt="Screenshot 2022-06-14 at 11 53 18" src="https://user-images.githubusercontent.com/158178/173561340-9d4bc4a5-3c63-46db-bf47-fc4534f7a103.png">

---

### Proposals accepted or refused
- When the voting phase has finished, the proposals should update their status and show if they've been approved or rejected
- Update icon colours to make it easy to distinguish and updated the copy to "Proposal accepted/rejected on DATE"

<img width="781" alt="Screenshot 2022-06-14 at 11 57 58" src="https://user-images.githubusercontent.com/158178/173562216-cdd4e240-fd75-45cf-95b0-29aa0368cb3b.png">

---

### New "Create Proposal" dropdown button

- Before there was not a central place to create proposals, you either had to select a specific user to remove it or go to group settings to find the right proposal type
- Add a Create Proposal button on the dashboard widget that allows users to easily create new proposals with the different type of proposals available
- The button should appear in every widget state (no one has created a proposal yet, when there are proposals to be voted on and when there are no active proposals)
<img width="791" alt="Screenshot 2022-06-14 at 12 28 12" src="https://user-images.githubusercontent.com/158178/173567011-f317347a-b132-45a5-b9cf-2d6448276348.png">

---

### Proposals Archival Process

- As discussed with @taoeffect, there is no need to have an "Archive Proposals" button as proposals should be archived automatically.
- Once everyone has voted on the proposal or when the expiration date is reached, the proposal voting process is finished and the proposal is either accepted or rejected. 
- Once this happens, a notification should be sent to all users, notifying them of the voting result - the link should go directly to that proposal, either it is in the dashboard widget or "see all proposals" modal
- Closed proposals can be showed on the dashboard widget for 24 hours after the proposal has been voted on and then should be archived automatically
- The dashboard widget should only show active/open proposals or proposals closed within the last 24 hours.

For more context view issue #924 Design/Implement Clear Proposals button


---

### Figma 

- Widget Variations: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23051%3A211402
- Create button dropdown: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23053%3A216181

@pieer assigning this to you. Please let me know if you have any doubts.

**Comment by taoeffect** [comment]
Awesome, closing in favor of implementation issue #1300.
