### ISSUE TITLE
Gameification designs for stories, streaks, and badges

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1305]
### Problem

There are several major problems:

1. The app has no built-in way for informing pledgers of the impact of their $
2. Recievers aren't incentivized to share their progress
3. Pledgers aren't incentivized to make timely payments

### Solution

We need to use streaks, badges, stories, and timelines to incentivize the following behavior:

- Pledgers: completing TODOs
  - completion streak
  - one additional idea is to include a separate state for "first sender", e.g. you can get ⭐ 's for each time you're the first person in a distribution period to make the payment. And there's a running counter on each pledger's profile showing how many of these they've gotten (if they've gotten at least one).
- Receivers: completing stories

We need a visual display of success rate:

- TODOs graph over time success rate (already an open issue: #1286)
- Timeline of stories/events from receivers

And prominently feature a share story button for receivers.

**Comment by dotmacro** [comment]
>     * Pledgers: completing TODOs  
>       * completion streak

Consider: how is this handled for a user who completes all TODOS when pledging, but has not pledged every month?

>     * Receivers: completing stories
>     * Timeline of stories/events from receivers

If we are adding stories, then everyone should be able to share stories because everyone is a recipient. 
For example, someone receiving _gardening help_ may wish to share their garden's progress, and someone receiving _mincome_ may wish to share recovery progress.

**Comment by taoeffect** [comment]
I think this can be closed. If the current designs @leihla came up with are insufficient we can open a separate issue for it.

Great work @leihla!!
