### ISSUE TITLE
Some issues with notifications display

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1315]
### Problem

Two problems:

1. Notifications sometimes look weird when their contents are too big
2. You cannot highlight/select the text of a notification. This can be a problem if someone wants to copy/paste an error they've seen.

<img width="473" alt="Screen Shot 2022-06-24 at 12 26 41 PM" src="https://user-images.githubusercontent.com/138706/175653995-5cc837da-8920-4f36-bab2-6542a128ddb4.png">

### Solution

1. Fix UI issues
2. If it is possible to preserve the ability to click on a notification and also highlight text within it, make it so

**Comment by snowteamer** [comment]
It is actually not impossible to select and copy notification text.

Although I agree it's quite difficult to do:
- Clicking on the notification instead triggers following the notification's associated link.
- Initiating a drag gesture on the notification text doesn't work. That's likely the point that should be worked on.

Then because of these limitations, the user would have to start dragging the pointer from outside the notification, which is a bit awkward...
![image](https://user-images.githubusercontent.com/64228468/177749952-9e8292b9-91fe-45c1-ab8c-6bed2f5c87fe.png)
