### ISSUE TITLE
Research log + pubsub software

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#132]
### Problem

Our architecture for storing and syncing messages doesn't exist yet. We need to decide now which direction is best to go in.

### Solution

1. Find a pubsub mechanism that we're going to use for "the life of the project", that treats server in centralized prototype as just an "always up peer". This pubsub mechanism needs to work with: orbit-db (or whatever we end up going with for the log), and also work well on a mobile device.
2. ***For the prototype*** we need to decide what we're going to use to create and store and distribute the log of events. Are we going to simulate it using Objection.js ORM and SQL? Or are we going to go straight to Orbit-db (or something similar)? If it's the same amount of work to do orbit-db as it is to finish the objection.js simulation, and if orbit-db works, then we should just start with orbit-db in the beginning.
    - Sub-concern: orbit-db seems to be the best for what we need, but still, we should confirm that. Also, are we really sure that orbit-db guarantees that messages are correctly ordered if all of them are retrieved?

**Comment by taoeffect** [comment]
Also, per our convo today, open up any issues that you encountered on the orbit-db project (if existing issues aren't already open).

**Comment by taoeffect** [comment]
This is a very handy/informative link: https://deepstream.io/blog/realtime-framework-overview/

Contains links to many interesting pubsub libraries, e.g. this one (an abstraction for a bunch of pubsub/websocket libraries): https://github.com/primus/primus

Also wondering, can orbit-db be used with a totally independent pubsub system?

**Comment by vijayee** [comment]
Per the issue created. Haad has version of the api that he targets in order to get orbit-db working. https://github.com/haadcode/orbit-db/issues/154#issuecomment-266185566

**Comment by taoeffect** [comment]
Done

**Comment by haadcode** [comment]
Hi! I hope you don't mind me posting an update here re. your questions above. This issue was referenced in one of the orbit-db issues and I thought, now with a new release, there's news to share :)

With 0.16.0, orbit-db now uses IPFS pubsub. Both js-ipfs and js-ipfs-api support it, meaning it also works in the browser version of orbit-db (and js-ipfs). The pubsub module in orbit-db is separated to  https://github.com/haadcode/orbit-db-pubsub which would be trivial to replace in OrbitDB https://github.com/haadcode/orbit-db/blob/master/src/OrbitDB.js#L9 to use another pubsub interface. Before IPFS pubsub existed, orbit-db used a Redis pubsub system and that used exactly the same interface as orbit-db-pubsub has now. So, to answer your question above, you could use any pubsub system with orbit-db.

More information on IPFS pubsub can be found from https://github.com/libp2p/js-libp2p-floodsub and https://github.com/libp2p/go-floodsub

> are we really sure that orbit-db guarantees that messages are correctly ordered if all of them are retrieved?

This is what orbit-db guarantees. However, there's a bug in the implementation that prevents orbit-db ordering the messages correctly (ie. you have to do it on app-level with a timestamp, which is not recommended nor desired solution), but once this PR https://github.com/haadcode/ipfs-log/pull/100 is merged, that problem will be gone and messages are ordered correctly. Bear in mind though that orbit-db only guarantees partial order, meaning they're not always in absolute chronological order. If you need total order, you still need to order them on app level using some mechanism (like timestamps).

Hope this helps!

**Comment by taoeffect** [comment]
Hey @haadcode thanks for popping in and sharing that info!

> The pubsub module in orbit-db is separated to https://github.com/haadcode/orbit-db-pubsub which would be trivial to replace in OrbitDB https://github.com/haadcode/orbit-db/blob/master/src/OrbitDB.js#L9 to use another pubsub interface. Before IPFS pubsub existed, orbit-db used a Redis pubsub system and that used exactly the same interface as orbit-db-pubsub has now. So, to answer your question above, you could use any pubsub system with orbit-db.

Nice! I see it's passable as an option via `options.broker`. Great job with that! 👍 

And thanks for the heads up on the message ordering. We've already gone forward with an "IPFS simulation" approach, so that means that if/when needed, we should be able to easily switch the code over to orbit-db. Am looking forward to seeing the project progress.
