### ISSUE TITLE
Bug in login code related to refresh during contract sync

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1334]
### Problem

In my testing of the live server login, I encountered a situation where login was taking too long. The white `Loading events from server...` banner appeared for a long time, so I refreshed the page.

Upon refresh, the group was no longer being joined, and the account I was logged in as was group-less.

When I re-added the account using the expired "anyone can join" invite link (which seemed to work because the group considered the account present), the account no longer had its income details specified. They also appeared in the "Members" list as a "NEW" member.

### Solution

This is really two separate issues, but I wanted to document both so that I wouldn't forget.

To recap, the two problems described:

1. Account leaving the group upon page refresh (this is the problem to fix for this issue)
2. Account losing income details (as a separate issue, figuring out why this happened, if this is a bug, and fixing it if so)

To fix the leaving group upon page refresh during login bug, I think requires modification to this code:

```js
  'gi.actions/identity/updateLoginStateUponLogin': async function () {
    const getters = sbp('state/vuex/getters')
    const state = sbp('state/vuex/state')
    const ourLoginState = generatedLoginState()
    const contractLoginState = getters.loginState
    try {
      if (!contractLoginState) {
        console.info('no login state detected in identity contract, will set it')
        await sbp('gi.actions/identity/saveOurLoginState')
      } else if (diffLoginStates(ourLoginState, contractLoginState)) {
        // we need to update ourselves to it
        // mainly we are only interested if the contractLoginState contains groupIds
        // that we don't have, and if so, join those groups
        const groupsJoined = difference(contractLoginState.groupIds, ourLoginState.groupIds)
        console.info('synchronizing login state:', { groupsJoined })
        for (const contractID of groupsJoined) {
          try {
            await sbp('gi.actions/group/join', { contractID, options: { skipInviteAccept: true } })
          } catch (e) {
            console.error(`updateLoginStateUponLogin: ${e.name} attempting to join group ${contractID}`, e)
            if (state.contracts[contractID] || state[contractID]) {
              console.warn(`updateLoginStateUponLogin: removing ${contractID} b/c of failed join`)
              try {
                await sbp('chelonia/contract/remove', contractID)
              } catch (e2) {
                console.error(`failed to remove ${contractID} too!`, e2)
              }
            }
          }
        }
      }
```

Specifically, there is clearly a call to `await sbp('chelonia/contract/remove', contractID)` there if an exception occurs.

Well, this normally would make sense, but in this specific scenario it doesn't. I also didn't see the console log when this happened, so I can't be 100% sure whether or not this is the cause, but you can try reproducing the problem by logging in to an account in a private window that is part of a group with a good number events, and before doing so enabling the browser's simulated bandwidth throttling tool. Then refreshing the page while the white banner is visible, and seeing what happens in the console during this whole time.

**Comment by Silver-IT** [comment]
To be clear, this ticket has separate two issues which have no relations between each other.
1. In my testing of the live server login, I encountered a situation where login was taking too long. The white Loading events from server... banner appeared for a long time, so I refreshed the page. Upon refresh, the group was no longer being joined, and the account I was logged in as was group-less.
2. When I re-added the account using the expired "anyone can join" invite link (which seemed to work because the group considered the account present), the account no longer had its income details specified. They also appeared in the "Members" list as a "NEW" member.

Since there are two separate issues, there must be two separate solutions as you described above.
@taoeffect , did I get it right?

**Comment by Silver-IT** [comment]
If I describe the first issue more in detail, we can see different two end results.
1. When `userA` refreshes the page while joining the group, others could see two equal notifications.
![image](https://user-images.githubusercontent.com/57976479/234482330-221b5b8c-7adf-4db9-9a4b-0a384799c33d.png)
2. When `userA` closes browser while joining the group, he is group-less when he try to login in another device later even though he is already joined the group. Others can see `userA` in the group members list.

**Comment by Silver-IT** [comment]
I think we should update(or remove) the `gi.contracts/identity/setLoginState` function which currently only saves the list of groupIds which the user is part of.

We can remove this `gi.contracts/identity/setLoginState` function, and make two functions instead.
`gi.contracts/identity/joinGroup`: add a new groupId to the groupIds in **process** and sync a new group contract in **sideEffect**
`gi.contracts/identity/leaveGroup`: remove the groupId from the groupIds in **process** and unsync the group contract in **sideEffect**
Also we can merge these two functions. Actually, this is the same behavior as to join chatroom through group and mailbox contract.

What do you think, @taoeffect?

**Comment by taoeffect** [comment]
@Silver-IT

> Since there are two separate issues, there must be two separate solutions as you described above.
@taoeffect , did I get it right?

Yes

> What do you think, @taoeffect?

I think adding `gi.contracts/identity/joinGroup` and `gi.contracts/identity/leaveGroup` might be a good idea. But I'm not sure what you mean by "merge these two functions"

**Comment by Silver-IT** [comment]
> I think adding gi.contracts/identity/joinGroup and gi.contracts/identity/leaveGroup might be a good idea. But I'm not sure what you mean by "merge these two functions"

Since those two functions are similar so I thought if it could be good if we do those two things in one function. Of course, there would be a parameter `joinOrLeave`. But I will make separate two functions. That seems better way.

**Comment by Silver-IT** [comment]
The new way of using `joinGroup` and `leaveGroup` identity contract functions leads to update the whole workflow of login process.
We **only sync the contracts** and do not call any actions like `'gi.actions/group/join'`, `'gi.actions/identity/updateLoginStateUponLogin'`, `'gi.actions/identity/saveOurLoginState'`.
![SignIn Flow Chart](https://user-images.githubusercontent.com/57976479/234739090-10dc9c1f-b20b-4c9a-aadb-f8834d12a901.png)

Signing-in means to sync contracts. Users can join/leave the same group several times and also join/leave the same chatroom several times too. We should not sync group and chatroom contracts in the sideEffect functions in order to reduce redundancies.

For example, when we join the chatroom, the chatroom contract is synced in `gi.contracts/group/joinChatRoom` sideEffect. But that sync should be ignored while signing in.

PS: When a new member joins the group, we (group members) sync his identity contract. But we didn't remove that identity contract when he leaves the group. So we only let group and chatrooms contracts not being synced while signing in.

EDITED: We should call a function `'gi.actions/group/updateLastLoggedIn'` at the end of the login process.

**Comment by taoeffect** [comment]
@Silver-IT 

> and unsync the group contract in sideEffect

I don't think the syncing and unsyncing should be done in the sideEffect because that might cause problems if you leave and rejoin multiple times.

**Comment by Silver-IT** [comment]
> I don't think the syncing and unsyncing should be done in the sideEffect because that might cause problems if you leave and rejoin multiple times.

To be honest, syncing contracts in `sideEffect` is the only way to fix the first issue (refresh page / close browser & open it in another browser while joining group). I know it might cause problems if we leave and join multiple times. I faced this problem when I was implementing `gi.contracts/group/joinChatRoom`.
Do you have any recommendation in your mind?

**Comment by Silver-IT** [comment]
I think this issue is no longer happening thanks to adding new functions (`gi.contracts/identity/joinGroup`, `gi.contracts/identity/leaveGroup`) in identity contract in the PR #1788. I think this issue should be **closed** of course after @taoeffect would check once more.
