### ISSUE TITLE
Design when the target message is deleted

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1343]
### Problem

When user tries to scroll to the target message for a reply message.
![image](https://user-images.githubusercontent.com/57976479/178613767-fa2ee0c5-7a9c-4a0d-aed1-92b9ac3406eb.png)

In the Discord, it shows that the original message was deleted.
![image](https://user-images.githubusercontent.com/57976479/178614008-4c152da1-2e23-4544-959b-55e670bc5950.png)
In Slack, nothing happens.
![image](https://user-images.githubusercontent.com/57976479/178614073-588c00ca-c4fe-46f9-9a5c-9042c762ab75.png)

What should we do?

### Solution

Make design or let us know what we should do. Even say `Nothing will be happening.`

**Comment by leihla** [comment]
@Silver-IT 

If the original message was deleted and there's a reply to it, instead of quoting the reply, just change the text to "Original message was deleted" as per Discord. 

<img width="887" alt="Screenshot 2022-07-15 at 11 34 51" src="https://user-images.githubusercontent.com/158178/179206896-1c7cb8fd-1e0e-49f8-9141-91a38bbc1729.png">

**Comment by Silver-IT** [comment]
Got it, @leihla.
