### ISSUE TITLE
Chat: do not refetch messages if not needed

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1374]
### Problem

Currently, switching back and forth between the dashboard and the chat will cause the chat messages to be refetched from the server each time.

### Solution

Don't refetch messages if it's not needed.

**Comment by Silver-IT** [comment]
This ticket points the really important issue and if we resolve this one, it will surely improve the performance.

Instead of fetching messages (actions) every time we enter a chatroom, we should save the stringified messages in browser storage and take it in advance to avoid the fetching all of those messages from backend.

~~Since more messages could be made after the messages are stored, we should also save `from` and `to` messages hashes just like the following.~~
```
messages: {
  [contractID]: {
    from: '', // the start message.hash()
    to: '', // the end message.hash()
    messages: '' // stringified messages object
  }
}
```

**EDITED: We should save events not only messages. That's because we need to render all the events when the user scrolls up. If we save only messages, we should get all the events again when the user scrolls up. So we should save stringified events.**

**Comment by Silver-IT** [comment]
#### The First Problem
We can get this stringified messages from browser storage every time we enter the chatroom, but the problem is that `When should the latest messages be saved in storage?`.

1. Every time a user leaves the chatroom page
2. Every time a user receives any chatroom action

#### Solution
I think the first option is more efficient way even though users can close the tab or browser unexpectedly.
Additionally, should compare `first` and `end` before save messages in storage to check if it's necessary operation or not.

**Comment by Silver-IT** [comment]
#### The Second Problem
The other important thing is the `from` value.
The longer a user is on the browser, the more messages would be saved in the storage. Even all the messages since the chatroom contract is created. That's not good in terms of memory usage.

#### Solution
If the number of messages stored in the storage is more than a `limit` (5 or 10 times of `CHATROOM_ACTIONS_PER_PAGE`), we can clear the messages in storage and make it empty.
Then, it will be filled with the acceptable number of messages when the user enters and leaves the chatroom next time.

**Comment by Silver-IT** [comment]
@taoeffect, I think the clear solution is shown above. Can you please check and share your opinion?

**Comment by taoeffect** [comment]
@Silver-IT What about just having a cache in memory for the _visibile_ messages of the *current channel*? That way if they click to another tab in the navigation, and then click back to the chat, it will be instant, but the moment they switch to another chat channel, or they scroll up, it will load them from the server. And this way we don't have to worry about storing and clearing anything in local storage.

**Comment by Silver-IT** [comment]
@taoeffect, if we save only the previous messages in storage, we need to load all the messages from Backend when switch 3 channels. I think the goal of this issue is to reduce the backend calling as much as possible.
So I think we should save the messages of all the chatrooms as long as it doesn't overflow the memory usage.

**Comment by taoeffect** [comment]
@Silver-IT The goal of the issue is to strike a balance between usability (the app being unreasonably unresponsive) and resource usage (on both the client and the server). Let's continue this discussion on Slack and then post a summary of what we conclude.
