### ISSUE TITLE
Dashboard info: total amount distributed

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1432]
### Problem

Something that would be very important for the group to know (and potentially advertise) is how much total $ it has distributed over the group's history.

### Solution

I've added 3 comments on Figma for the 3 locations where I think this info should be added:

- https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN?node-id=23342:251273#279001752
- https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN?node-id=23342:251404#279001846
- https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN?node-id=23766:357406#279001896

**Comment by leihla** [comment]
@taoeffect 

I've added the Total Distributed Since start to the Support History Tab. I agree with @dotmacro that we should not show that information on the TODO% tab nor the Activity as they should different metrics.

With this, and as I believe the calculations for the support haven't been done yet, what exactly do we want to show? Mincome goal reached, Total amount covered and distributed? I've left you a comment here 

https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN?node-id=23342:251273#311793780

**Comment by SebinSong** [comment]
Hi @taoeffect,

<img src='https://user-images.githubusercontent.com/17641213/207286134-3da708d1-8ec5-44ad-b732-464ddc5de4d0.png' width='414'>

I was trying to figure out what would be the best way to implement this 'total pledges since start' value, and decided to add a field named something like `totalPledges` in group state and make the app update this value each time a payment is  processed. Does it sound like a good idea to you as well?
Thought it would be better than going through all payment period history of the group and sum up the payment items  every time the user visit the UI. pls let me know if you have any other opinion.

Thanks,

**Comment by taoeffect** [comment]
> I was trying to figure out what would be the best way to implement this 'total pledges since start' value, and decided to add a field named something like totalPledges in group state and make the app update this value each time a payment is processed. Does it sound like a good idea to you as well?

Yes, I agree, this way you don't have to worry about old payments that are going to be archived and removed from the state anyway. It's really the only way to do it, I think.
