### ISSUE TITLE
Listening for message hash in prepublish hooks isn't safe!

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1487]
### Problem

As shown in this code for `cy.giForceDistributionDateToNow`:

```js
Cypress.Commands.add('giForceDistributionDateToNow', () => {
  cy.window().its('sbp').then(sbp => {
    return new Promise((resolve) => {
      sbp('gi.actions/group/forceDistributionDate', {
        contractID: sbp('state/vuex/state').currentGroupId,
        hooks: {
          prepublish: (message) => {
            sbp('okTurtles.events/on', message.hash(), resolve)
          }
        }
      })
    })
  })
})
```

We are listening for `message.hash()` event - BUT, as @snowteamer very astutely observed, this isn't safe! Messages can be re-created by `'chelonia/private/out/publishEvent'`, causing the hash of the successful message to be different, resulting in a hanging promise.

### Solution

Find all such uses of `prepublish` or `prepublishContract` in the code, and replace them with listeners for `EVENT_HANDLED` (as emitted by `internals.js`), and in the listener compare on the ~~`message.message().previousHEAD` instead of the message's hash.~~ Add a comment explaining all of this so that people who read the code aren't confused.

EDIT: NO! The previousHEAD will be different too (because a message got squeezed in between)! So, perhaps the best way to deal with this is to compare on the `JSON.stringify(message.opValue())`, as that should be the same

**Comment by Silver-IT** [comment]
@snowteamer, you catched a really important issue in  the `prepublish` hook and `chelonia/private/out/publishEvent` function. Nice work!!!

And in the solution, @taoeffect recommended the way to solve this issue which is to by comparing `opValue()` instead of `message.hash()` or `message.message().previousHEAD`.
But what I am thinking is that this solution could break in some cases (Especially, if an event with the same params would be occured). Also, we can not call `prepublish` hook as soon as the event is published successfully (in the 144 line of `internals.js`) because it's actually `postpublish`.

So I also think that we could make a function in GIMessage to update **only** previousHEAD. What do you think, @taoeffect?

**Comment by Silver-IT** [comment]
We can't update **only** `previousHEAD` without the change of `message.hash()`.
So instead of making a new function to update **only** `previousHEAD`, we can make a function (similar to createV1_0) to create a message but **with a specified nonce**.
And then we can define `message.id()` by the `message.opValue()` and `nonce`.

**Comment by taoeffect** [comment]
> But what I am thinking is that this solution could break in some cases (Especially, if an event with the same params would be occured).

It's true that's a theoretical possibility, but where we use this it's extremely unlikely.

> Also, we can not call prepublish hook as soon as the event is published successfully (in the 144 line of internals.js) because it's actually postpublish.

Not sure what you mean, line 144 of internals.js is:

```js
      if (r.ok) {      // <-- line 144
        return r.text()
      }
```

> So I also think that we could make a function in GIMessage to update only previousHEAD. What do you think, @taoeffect?

I'm not sure what you mean, so I can't answer. Can you elaborate a bit more?

> So instead of making a new function to update only previousHEAD, we can make a function (similar to createV1_0) to create a message but with a specified nonce.
And then we can define message.id() by the message.opValue() and nonce.

Maybe... that's an interesting idea. We could do that! However, since it involves the `nonce`, and since @corrideat removed it in his PR, let's [wait until we figure out why he did that](https://github.com/okTurtles/group-income/pull/1257#pullrequestreview-1296628304) before doing this. For now we can rely on `.opValue()`, and I agree, it's not perfect, but it's good enough for now.

**Comment by Silver-IT** [comment]
> Not sure what you mean, line 144 of internals.js is:

I mean just before `return r.text()`. But it's after the event would be already published, so it's not `prepublish` actually. It's `postpublish`.

> I'm not sure what you mean, so I can't answer. Can you elaborate a bit more?

I thought if we could update only `previoudHEAD` using a new GIMessage function, so that we could compare message using the same hash. But a few mins later, I noticed that it's not possible to update only `previousHEAD` without any changes of message.hash(). So we can not use message.hash() for the comparison key.

**Comment by Silver-IT** [comment]
I think there should be a way to identity GIMessage. I think we can make a GIMessage.id() just using `nonce` and `previousHEAD` or something else.
In order to do this, there should be a GIMessage function to create an GIMessage instance with a specific nonce.
If we want to create a GIMessage which has only difference in `previousHEAD`, we can not do this at the moment.
