### ISSUE TITLE
Followup to Notifications System PR

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1509]
### Problem

As mentioned in [the review](https://github.com/okTurtles/group-income/pull/1497#pullrequestreview-1324904235), there are 2 remaining things to be done for the notifications system:

1. [Handling expiring proposals notification](https://github.com/okTurtles/group-income/pull/1497#discussion_r1121173815)
2. Using `dateToPeriodStamp` where appropriate (e.g. [here](https://github.com/okTurtles/group-income/pull/1497#pullrequestreview-1324866866) and [here](https://github.com/okTurtles/group-income/pull/1497#pullrequestreview-1324902737), and anywhere else I missed)

### Solution

Do those things :)

**Comment by SebinSong** [comment]
Hi @taoeffect ,
I'm currently looking at  1. [Handling expiring proposals notification](https://github.com/okTurtles/group-income/pull/1497#discussion_r1121173815) in the list. What sentence should we use for the 'PROPOSAL_EXPIRING' notification copy and what's the expected action when the notification is clicked on?

**Comment by taoeffect** [comment]
@SebinSong How about either: “An open proposal is about to expire, please vote!” Or: “Proposal about to expire: {proposalTitle}”

When they click on it take them to the dashboard and scroll them to the proposals section (perhaps using an anchor tag)

**Comment by SebinSong** [comment]
Hi @taoeffect ,
Got a follow-up question for the expiring proposal notification.

Quote from your original comment [here](https://github.com/okTurtles/group-income/pull/1497#discussion_r1120993891)
> So the idea is ultimately to notify the user of something without touching the contract code.... and I'm trying to figure out what this code does and where the notification is ultimately sent. And I'm coming to the conclusion that the notification itself was never implemented!

Actually `gi.actions/group/notifyExpiringProposals`([here](https://github.com/okTurtles/group-income/blob/4675aab76b63524c05483e0ab1d890aa5105f24a/frontend/controller/actions/group.js#L476)) results in a notifying message in the chatroom like below screenshot. But since it's chatroom message, this 'gi.action' call does involve touching the contract code which is `gi.actions/chatroom/addMessage`. Should we keep this existing logic and also implement 'PROPOSAL_EXPIRING' notification or should we remove this logic and replace it with the notification?

<img src='https://user-images.githubusercontent.com/17641213/223589944-ca580e4f-2f8e-429c-84bb-de0c78e165d7.png' width='520'>

**Comment by taoeffect** [comment]
> Actually gi.actions/group/notifyExpiringProposals(here) results in a notifying message in the chatroom like below screenshot.

The codebase has gotten so huge I missed this! Great catch!

> Should we keep this existing logic and also implement 'PROPOSAL_EXPIRING' notification or should we remove this logic and replace it with the notification?

I like it, I think it's good to have it in both places to really make sure people see it, so let's keep this existing logic and also implement the notification 👍
