### ISSUE TITLE
Flickering when switching to and from chat

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1531]
### Problem

Is there a way to reduce the flickering seen here?

![a mov](https://user-images.githubusercontent.com/138706/230535090-92dff1d4-361e-4cac-a366-752027f7f87f.gif)

### Solution

Ideally, the messages would instantly appear with no flickering (unless they need to be loaded). Since these messages were recently loaded, there shouldn't be any flickering, especially because #1374 was closed.

**Comment by Silver-IT** [comment]
As you know, we save events and don't save messages in the `Indexed Storage`. That's because we should save events and render previous and upcoming events using them.

So we should render events in order to make the list of messages. And also if less than one page of messages loaded, we should try to get more events to fill the page. So the infinite loading would work at least once in this case.

My solution is that, I just hide the content and display a spinner at the bottom until the messages are initially loaded inside the channel just like how Slack does.
