### ISSUE TITLE
Proposal expiring reminder should result in multiple notifications

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1540]
### Problem

![Screen Shot 2023-04-16 at 4 28 21 PM](https://user-images.githubusercontent.com/138706/232349362-7a0b87a8-9d50-4fa5-b670-85985f6568bf.jpg)

Although the fact that a proposal is about to expire gets posted to the chat, there is no sound, no posted notification from the web browser to the computer, no red dot on the chat notifying of new messages, and no notification on the bell icon either.

### Solution

Add all of these:

1. notification under bell icon
2. red dot on chat indicating that there's a new message
3. post a browser notification from the browser with a sound

And check the other notifications to see if they also should do this.

**Comment by dotmacro** [comment]
While I did not get any notification about the auto-message posted in chat, I did get:
- an auto-notification under the bell icon
- a red dot on the bell to let me know there was a new notification
- a red dot on the favicon to let me know to check the tab for a notification

**Comment by taoeffect** [comment]
@dotmacro interesting, are you sure it was specifically for that notification and not something else?

**Comment by dotmacro** [comment]
Yes. That was my only unread notification, so I'm almost certain both red dots were for the "proposal about to expire!" notification. (The previous notification was from 10 days ago.)

![image](https://user-images.githubusercontent.com/13082264/232355793-c0a4b969-7391-46b5-a500-aacde0ab9eca.png)

**Comment by taoeffect** [comment]
Interesting! I didn't get that notification at all. 🤔

**Comment by SebinSong** [comment]
@taoeffect , @dotmacro Let me try the scenario by myself too and work on fixing it if I encounter the issue!

**Comment by SebinSong** [comment]
@taoeffect 
When you saw the notification for an expiring notification in the general group channel, Had you already voted for that particular proposal?
Currently, the periodic notification entry for an expiring proposal(please refer to  **[here](https://github.com/okTurtles/group-income/blob/b429340e0849202be453b8e3044183a24273c19e/frontend/model/notifications/mainNotificationsMixin.js#L152)**) **only** sends the pop-up notification(That notifications we check from the bell icon button) to the users who haven't voted for that particular proposal yet. That can be why @dotmacro received it but you didn't. (@dotmacro could you confirm it?)

This same logic will also send a notification in the 'General' channel, and since it's a message in **'General'** channel, it's exposed to **every** users regardless of whether they've completed their votes or not.

This is my guess from going through the chain of relevant logics in the app. (But If this is not the case, I will go on and do further investigation.)

**Comment by dotmacro** [comment]
> Currently, the periodic notification entry for an expiring proposal(please refer to [here](https://github.com/okTurtles/group-income/blob/b429340e0849202be453b8e3044183a24273c19e/frontend/model/notifications/mainNotificationsMixin.js#L152)) only sends the pop-up notification(That notifications we check from the bell icon button) to the users who haven't voted for that particular proposal yet. That can be why @dotmacro received it

That's correct, I hadn't voted for that particular proposal.

**Comment by SebinSong** [comment]
@dotmacro thanks for confirmation

**Comment by taoeffect** [comment]
>  When you saw the notification for an expiring notification in the general group channel, Had you already voted for that particular proposal?

Yes I think so, but I can't be sure that I voted before that notification appeared in the channel. It could have appeared there and I didn't know, and then voted, and then saw it. Not sure. But I did vote in the poll before I saw it.

> Currently, the periodic notification entry for an expiring proposal(please refer to here) only sends the pop-up notification(That notifications we check from the bell icon button) to the users who haven't voted for that particular proposal yet. 

Ooooohhh!! That makes sense!

However, then why did @dotmacro not get the chat notification?

> While I did not get any notification about the auto-message posted in chat

**Comment by SebinSong** [comment]
@taoeffect That's something I'm going to investigate & work on. I guess below message-type is currently missing that feature.

![image](https://user-images.githubusercontent.com/17641213/232923933-dd16834f-557c-4e26-8d69-9f587c06bf8a.png)

**Comment by SebinSong** [comment]
@taoeffect According to discussion with Alex on Slack general chat, he made a fix for similar issues in [this ongoing PR](https://github.com/okTurtles/group-income/pull/1534). So I think it should wait until that PR is merged to `master`, re-check if this issue still persists after pulling that change and then work on the fix if so.

**Comment by taoeffect** [comment]
@SebinSong Alright 👍
