### ISSUE TITLE
Duplicate notifications when someone joins on both desktop and mobile

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1575]
### Problem

When someone joins first on desktop, and then logs in on mobile, I got this duplicate notification.

![Screen Shot 2023-05-04 at 9 19 18 PM](https://user-images.githubusercontent.com/138706/236376960-995cd597-7f92-4db5-87ef-fa4db3760877.jpg)

I also got the duplicate notification on my mobile device (where I was also logged in).

### Solution

Find and fix the problem.

**Comment by Silver-IT** [comment]
Finally, I have found the reason. It's in calling `accept` function in `Login` form in `Join` page.
Steps to reproduce (which I guess, Not sure if there is more)
- UserA signup and creates a groupA
- UserA shares the invitation link with UserB
- UserB signup and join the groupA
- UserB logs out
- UserB open the invitation link again
- UserB sees Signup form by default but he has already signed up
- UserB switches to Login form and tries to login with his credential
- BANG

That's because `accept` function is calling the `'gi.actions/group/joinAndSwitch'` sbp function no matter it's `Sign Up` or `Login`, `Joined` or `Not yet joined`.
