### ISSUE TITLE
Page doesn't refresh on new version

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1629]
### Problem

Try the following:

1. Delete `data/groupincome.db` and run `GI_PERSIST=sqlite grunt dev`
2. Create a group and go to the chatroom, post a message
3. Stop the server with `^C` and make some changes to the chatroom contract, then run `grunt pin:0.1.5`
4. Run `GI_PERSIST=sqlite grunt dev` again

The open page you were logged in on will reconnect but won't refresh. It should refresh.

### Solution

Find and fix bug.

**Comment by snowteamer** [comment]
In this scenario, i.e. manually closing and restarting the server, the client is only supposed to reload in production mode, but not in development.
More precisely, the pubsub server is configured so that when the backend is up again and the client reconnects, the server will send a message with the new `GI_VERSION`, but only if in production mode:

https://github.com/okTurtles/group-income/blob/f16cd059782bb5cbd3eccddae92d1b1e9fe1f89d/backend/server.js#L86-L94
In development, app reloading is managed by BrowserSync, but only as long as the grunt process is running. Shutting down the process by issuing a ^C disables any file watching.

So if we sent a new `GI_VERSION` in development too, then the page might reload twice in the usual case (BrowserSync reload + version change reload). Unless maybe we don't append a timestamp to `GI_VERSION` in development, while still doing it in production.

Otherwise, in dev mode maybe we should be able to issue grunt commands in another terminal tab, rather than have to Ctrl-C the server first. When I tried `grunt pin:0.1.5` in another CLI tab, while the backend server was running, the page did try to reload but failed. 😕
