### ISSUE TITLE
Update error message and make it more informative

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1727]
### Problem

When we try to login with the wrong password, we get the following error message.
![image](https://github.com/okTurtles/group-income/assets/57976479/4f931c0e-3b1c-4863-9cea-6e7196134360)

### Solution

It should be something more informative.
`Username doesn't exist` or `Incorrect password`.

**Comment by Silver-IT** [comment]
My suggestions for the error messages are `Incorrect  username`, and `Incorrect password`.
@leihla, can you please add error messages in [this Figma design](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=1918-29&mode=design#208301648)?

cc: @taoeffect

**Comment by taoeffect** [comment]
@Silver-IT Try, “Incorrect username or password.” for both

**Comment by Silver-IT** [comment]
Yeah.

**Comment by taoeffect** [comment]
Note: ~~I had to undo #1731 because it broke the flow after logging in and creating a group - no longer correctly redirected to dashboard upon group creation.~~

@corrideat maybe you know why?

EDIT: maybe it wasn't Alex's PR... I'm getting the same exact issue in `e2e-protocol-ricardo` now.

EDIT2: moved issue to: https://github.com/okTurtles/group-income/issues/1720#issuecomment-1773278280

This wasn't your fault @Silver-IT! I undid the revert commit and am closing this issue.
