### ISSUE TITLE
[e2e-protocol] Proposals widget misbehavior when rejoining a group

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1737]
### Problem

![Screenshot 2023-09-22 at 10 10 06 AM](https://github.com/okTurtles/group-income/assets/138706/057b8540-d1e1-456b-b183-e870eacf9255)

1. Create a group and join 5 users: u1, u2, u3, u4, u5
2. u1 creates proposal to remove u4
3. u2 and u3 vote to remove u4
4. u4 rejoin group using original invite link

Duplicate key errors and multiple proposals shown for u4 (when viewing group as u4 upon rejoining)

### Solution

Find and fix the bug.

Please branch off of `e2e-protocol` where this bug is, and send in a PR to that branch, not `master`.

**Comment by Silver-IT** [comment]
@taoeffect, I have tested this issue in `master` branch as well. That's because I found the reason of this issue which could be cause in`master` branch either.

In `master` branch, it happens too when we click `Archived Proposals` button.

SOLUTION: We should remove archived data (proposals, payments) for the group when leave the group.

**Comment by taoeffect** [comment]
~~Closed by @Silver-IT in #1747!~~ EDIT: nope, I should have done a better job testing.

**Comment by taoeffect** [comment]
Nope, this is still an issue.

**Comment by Silver-IT** [comment]
Yeah, this issue actually exists in the `e2e-protocol` branch even though the PR is already merged.
I don't think it's because of the group contract issue, it would be because of e2e part, especially login process.
I can see that the messages are executed several times when login. I will keep this issue and test again after e2e part is more stable.

**Comment by Silver-IT** [comment]
I don't think this issue is still happening now, but I can see that duplicated notifications after rejoining group.
![image](https://github.com/okTurtles/group-income/assets/57976479/4dcd9a81-2cbe-484e-9cd4-192c8b64bb0f)
I will close this issue, and create a [new one](https://github.com/okTurtles/group-income/issues/1838) for the duplicated notifications because they don't seem to be related to this issue.
