### ISSUE TITLE
Completed payment not shown after entering a new period

### ISSUE THREAD

**Issue by snowteamer** [okTurtles/group-income#1739]
### Problem

Payments completed in the **previous** distribution period sometimes disappear from the Completed tab in the Payments page. Other payments are not affected.
 
 Steps to reproduce:
 
1. Create a $1000 group with u1 and invite u2
2. u1 income details pledging $100, u2 making $800
3. Enter the first distribution period by running:

   await `sbp('gi.actions/group/forceDistributionDate', { contractID: sbp('state/vuex/state').currentGroupId })`

4. Wait until the promise is resolved. Note that at this point, `getters.groupPeriodPayments` only holds an entry for the waiting period. It doesn't have an entry for the new current period yet.
5. Record a full payment as u1 to u2. It should show up in the Completed tab.
6. Now `getters.groupPeriodPayments` has **two** entries, one for the waiting period and one for the current period. That's a bit confusing.
7. Run `forceDistributionDate` again. The payment disappears from the Completed Tab.

### Solution

Fix it!

**Comment by Silver-IT** [comment]
@snowteamer, having tested this on my side in the latest `master` branch, the completed payments are not disappeared in the `Completed` tab after running the `'gi.actions/group/forceDistributionDate'` sbp function in console.

Also I don't have any opinion about having two entries in `getters.groupPeriodPayments` in step 6. Because the payment periods are now in the `DLL(Doubly Linked List)`, and no constant payment period we are using. And also `forceDistributionDate` function is only available in development mode.

@snowteamer , I need your reply.

cc: @taoeffect

**Comment by snowteamer** [comment]
@Silver-IT The disappearing payment bug might have been fixed in PR #1691, where I updated some methods in `PaymentsMixin.js`. This would explain why it didn't show up in your tests

**Comment by taoeffect** [comment]
Closing as this seems to have been fixed. Feel free to re-open if it hasn't!
