### ISSUE TITLE
Issue with offline handling for loading lazy loaded views

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1803]
### Problem

*Note: the screenshot for this issue is taken from Firefox Developer Edition (FDE). I've noticed that in the Network tab when you set "Throttling" to "Offline", the behavior is different between FDE and Chrome. In FDE the white "offline" banner doesn't appear when you set Throttling to Offline, because it seems there's a bug in Firefox that doesn't disconnect the web socket in that mode, whereas Chrome correctly handles this. Please test both browsers as you're debugging this issue.*

![Screenshot 2023-12-30 at 2 19 12 PM](https://github.com/okTurtles/group-income/assets/138706/52878348-3465-481f-9b94-b1039087e96c)

When setting the browser to "Offline" mode via the Network Throttling tab, and then clicking an unloaded page (e.g. the Chat view), you see this screen. However, when going back online, and then switching to the Dashboard and back to the unloaded Chat view, this error doesn't disappear, and no attempt to re-load the resource is made.

### Solution

Try and reload the page when we switch back to it, in case we're back online.

**Comment by SebinSong** [comment]
@taoeffect
This issue apparently is caused by the fact that the `vue-router` caches the previous resolved page content and keeps on using it from that point on. I've spent a few hours on any router option to customise this caching behaviour but haven't found any useful resources for the solution.
But also what I've observered is, if the browser refreshes the page, this router cache is cleared as well and the page reloads properly.

So as an alternative solution, I would love to suggest that, if the user is in that 500 server-error page but the browser detects it's online(reference [here](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine)), we reveal a little `retry` or `refresh` button that reloads the page. Does it sound good?

Thanks,

**Comment by taoeffect** [comment]
> So as an alternative solution, I would love to suggest that, if the user is in that 500 server-error page but the browser detects it's online(reference [here](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine)), we reveal a little retry or refresh button that reloads the page. Does it sound good?

Yeah, that does sound like good idea 👍
