### ISSUE TITLE
Update z-index of modal compared to the sidebar

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1843]
### Problem

We have `frontend/assets/style/_variables.scss` which defines the SCSS variables we are using in the whole frontend styles.
I have one thing weird here that `$zindex-modal` and `$zindex-sidebar` is same.
If these two things are same, which one would be on top of the other? Sidebar? Modal?
It depends on the how early it is rendered. So if modal is rendered before the sidebar, the sidebar would be on top of the modal.
And if the sidebar is rendered earlier, than the modal would be on top of the modal.
It happens while we create a poll. Clicking the sidebar doesn't not close the `CreatePoll` modal.

### Solution

Update `$zindex-modal` or `zindex-sidebar` so that `$zindex-modal` would be bigger than `$zindex-sidebar`.

**Comment by SebinSong** [comment]
@Silver-IT 

**1.**
> If these two things are same, which one would be on top of the other? Sidebar? Modal?


```
index.html
...
      <router-view v-if="ephemeral.ready" class="l-page"></router-view>
      <modal class="l-modal"></modal>
...
```

I believe sidebar is rendered as part of `<router-view>` here. and `<modal />` is located below that in the DOM tree if you look at the `index.html` file. So I'm pretty sure modal will be rendered on top of the sidebar as you said in the description.

**2.**
> Clicking the sidebar doesn't not close the CreatePoll modal.

I'm the one who built that `CreatePoll` component and it's just FYI this particular modal doesn't get rendered as a child component of `Modal.vue`, which is a typical way of building other modals in the app(e.g. Building the component using `ModalTemplate.vue` and then registering them in `lazyLoadedView.js`). But instead, it is a child component of `SendArea.vue` and is rendered as sort of an overlay component in the chatroom rather than a global modal of the app. 

And I would love to suggest that we fix this issue by just updating the z-index value of `.c-create-poll { ... }` in `CreatePoll.vue` to `$zindex-modal + 1;` instead of changing the value of `$zindex-modal` variable itself because that can lead to creating some unpredicted issues in other places.

**Comment by Silver-IT** [comment]
> I believe sidebar is rendered as part of <router-view> here. and <modal /> is located below that in the DOM tree if you look at the index.html file. So I'm pretty sure modal will be rendered on top of the sidebar as you said in the description.

Yes. That's because we can't find anything wrong while using Modal.

> And I would love to suggest that we fix this issue by just updating the z-index value of .c-create-poll { ... } in CreatePoll.vue to $zindex-modal + 1; instead of changing the value of $zindex-modal variable itself because that can lead to creating some unpredicted issues in other places.

It can solve the issue regarding CreatePoll component. I will listen to your suggestion, @SebinSong.
