### ISSUE TITLE
Implement uploading file attachments in chat

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1846]
### Problem

We can attach files to the chat, but they aren't actually uploaded.

### Solution

1. Upload the file attachment.
2. After it's uploaded, send the message, and reference the file attachment so that it's displayed inline along with the message.

See also companion issue #1845 which gives more detail about how this should be done.

**Comment by corrideat** [comment]
There are now two selectors for managing downloading and uploading files:

- `chelonia/fileUpload`
- `chelonia/fileDownload`

In addition, there are various selectors used for caching (`gi.db/filesCache`), which should _not_ be used for this issue (otherwise, the cache could be filled up quickly with large chat files).

Example usage for these APIs can be seen in the how the avatars are handled. But basically, when one calls `chelonia/fileUpload`, one gets an object in return, which can be then passed to `chelonia/fileDownload` to do the download and decryption. The result from `chelonia/fileDownload` is a `Blob`.

ETA:

`chelonia/fileUpload` gets called **once** per file and `chelonia/fileDownload` can get called as many times as needed. The result of `chelonia/fileUpload` therefore needs to be saved somewhere in the action for uploading the file so that then `chelonia/fileDownload` can get called.

The process would look something like this:

1. `Alice` wants to upload a file. She calls `const r = chelonia/fileUpload(...)`. Then, she sends an action to the chatroom, for example using `gi.contracts/chatroom/addMessage` and embeds `r` somewhere in the action.
2. Then, when `Bob` receives the message, he can recover the value for `r` and call `chelonia/fileDownload` with that to fetch the file.

`chelonia/fileDownload` takes a second optional parameter that's a callback function that gets called with the manifest file _before_ the file is downloaded. This is helpful because it includes the file size, so, for example, small files could be downloaded automatically but large files could require interactivity.

**Comment by SebinSong** [comment]
@Silver-IT I'm interested in working on this one too (per your suggestion in a Slack thread) but it appears that it would be more ideal that this is done as a follow up work of the issue #1845 which I think you are the better person to work on (as you have more in-depth knowledge re chatroom contracts). So if it sounds good, I can wait until #1845 is done and start working on this one.

**Comment by SebinSong** [comment]
Hi @taoeffect 

Been researching on this issue along with #1845  and it sounds like these two are very closely related to each other and completion of this issue actually requires completing #1845  whose main goal is to achieve below.

> We want to make sure the UI is not locked up while waiting for the image to upload, and we want them to also be able to continue sending other messages in the meantime.  

But in order for the job to feel smoother for us, I would love to suggest working on this issue in two steps(meaning two consecutive PRs), as below.

**[ Step1 ]** **Non-graceful implementation of file-upload.**
- As soon as the user attaches the files to the chat, the file upload process starts (using `chelonia/fileUpload`).
- while waiting for files to upload, show some kind of progress UI animation and also the **'Send' button is disabled**.
- Implement file download in the `Message.vue` component using `chelonia/fileDownload`

**[ Step2 ]** 
- Implement graceful handling of file-upload for all these procedures in **Step1** above. ('Send' button is not locked up, the chat messages can re-arrange if the file-upload takes long etc..)

Does it sound good to you as well?

Thanks,

**Comment by taoeffect** [comment]
Yes @SebinSong, that sounds like a good plan 👍
