### ISSUE TITLE
Implement deleting attachment of message

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1879]
### Problem

There are two features for the attachments in the message. One is `Download` and the other is `Delete`.
Download feature is done, but `Delete` feature is not yet.

### Solution

Create a `gi.contracts/chatroom/deleteAttachment` function and implement it.

**Comment by taoeffect** [comment]
I think for this issue, in addition to implementing support in Vue and the contracts, we need to implement a backend API to support file deletion. So this will have to wait on the proposal that @corrideat is working on to be implemented, because the server needs to do the following:

- It needs to have an API, e.g. `/fileDelete`
- It needs to be able to verify that the person who is calling this API has permission to delete the file
  - This is easier said than done. For example, we probably want to allow different parties to be able to delete a file. E.g. the group admin should be able to delete the file, and so should the server admin, and of course the person that uploaded it, but nobody else.
- Finally, we need to support updating the accounting for how much is being charge for storage so that the file is no longer being charged for
