### ISSUE TITLE
Store notifications in server-side KV store

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1936]
### Problem

Currently, the read status of notifications is per-device.

![Screenshot 2024-04-17 at 8 41 39 AM](https://github.com/okTurtles/group-income/assets/138706/223d4bef-c780-4a8c-b8df-a7df1740d1dd)

So when notifications are dismissed or cleared, they must be dismissed or cleared again in another browser or different device, or if someone logs out and logs back in again.

This is annoying.

### Solution

PR #1912 recently introduced a server-side authenticated and encrypted key-value store that can be used to solve this problem.

That PR used it to update `'gi.actions/group/updateLastLoggedIn'` to store the `lastLoggedIn` information for for the group contract.

The key-value store is scoped for a specific contract. In PR #1912, the `lastLoggedIn` information is stored under the group contractID so that there's a single place to look for the latest information about everyone's `lastLoggedIn` information.

For this issue, you'll need to scope the notifications key under the user's identityContractID and store all of the notifications under that key.

Very important: as over time there can be a lot of notifications, make sure that only the N most recent notifications are stored. I believe we already do this (see `MAX_COUNT` in `frontend/model/notifications/storageConstants.js` and `applyStorageRules` in `frontend/model/notifications/utils.js`).

Also: remember to make use of the KV-store's pubsub feature so that when a notification is marked as read or removed on one device, it instantly happens on any other open device. Likewise, clients should re-read the notifications key to get the latest value upon page refresh/logging in *and* re-establishing a connection to the server.

**Comment by dotmacro** [comment]
During testing today, I noticed that the `INCOME_DETAILS_UPDATE` notification on the dashboard also seems to be per-device / per-browser. 

1. Dismissed notification & updated income details in browser1. 
2. Opened browser2 and signed in. 
3. Notification visible at top of dashboard on browser2, even after hard refresh. Notification remains dismissed (i.e. not visible) on browser1.
<img width="828" alt="updateIncomeDetails" src="https://github.com/okTurtles/group-income/assets/13082264/23b4f84b-4b0b-4973-8f41-0d9c718fd921">

**Comment by taoeffect** [comment]
@dotmacro yeah that would be a separate issue, feel free to create it

**Comment by dotmacro** [comment]
> @dotmacro yeah that would be a separate issue, feel free to create it

Created new issue #2056

**Comment by Silver-IT** [comment]
@taoeffect, while I was investigating this issue I noticed that we should save only the `read` status of notifications, instead of all the notifications, in KV store with the following reasons;
- To store all the notifications (even though we have limit on number of notifications which is `MAX_COUNT`), that could be much because they should be saved **in every identity contract space** and **all notifications are Object**, not simple text or simple number.
- The another reason is that we are creating notifications while **syncing contracts**, and **in all the devices**. This means that we need a hash for every notification to identify them as long as we create them in all the devices. Furthermore, we don't need to save notification in KV store as long as we have its hash.
- I also noticed that we remove notifications only when users leave a group. Of course, the notifications only from the group they leave. And since it's what is handled inside the `gi.contracts/group/leaveGroup`, we don't need to think about syncing it using KV store pubsub. So now, the only thing we need to save is that the read status of notifications.
  - Even though we would add feature to remove a notification in the future, I think it's similar to how we handle the read status of notifications.

So, what I suggest is to define the type to just like the following.
```
[identityContractID]: {
  unreadMessages: {},
  preferences: {},
  notifications: {
    [hash]: { read: true/false }
  }
}
```

**Comment by taoeffect** [comment]
> So, what I suggest is to define the type to just like the following.

Yes, that looks good.

Very important to keep in mind though that it's possible for different devices to have different notifications.

In fact, your suggestion to not store the notifications in the KV store, and only store whether or not they've been read, is a very important idea, because this allows for different devices to show different notifications.

The reason is this:

- Some devices might have side effects that fail for whatever reason when they are logging in and syncing the contracts for the first time. In my tests this has happened. On desktop the login works fine, but on mobile some errors happened.
- So for this  reason different devices would show different notifications.
- Therefore, we do not want to store the notifications in the kv-store, they should be local to the device.
- But for notifications that appear on both devices, we should sync whether or not they have been read.

The challenge here is how will you create the hash from the notification?

You will need to make sure the hash of the notification is the same on both devices. One way is to use `JSON.stringify` on the notification object, and then create a hash out of that string. As long as the information in the object is the same on both devices, it should result in the same hash. Note: if the notification has information that might be unique to the device, for example the time when the notification was posted, then it will not have the same hash.
