### ISSUE TITLE
Emojis panel appears in wrong place

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1937]
### Problem

On desktop in Brave, I clicked on the emojis icon and the panel appeared way up in the upper-right:

![Screenshot 2024-04-17 at 10 28 49 AM](https://github.com/okTurtles/group-income/assets/138706/3a71026a-d50d-483a-a571-d2d9872c0610)

### Solution

The panel should appear next to the emoji button, check Slack or Discord for how this should be done.

**Comment by Silver-IT** [comment]
Having tried many tests this issue, I can say that this issue is not related to the Brave browser.
This kind of wrong positioning error happens when we try to test with resizing browser. While testing the emoji after getting back from the shortening the browser width, we can see this issue is happening.

**Steps to reproduce**
- Test emoji
- Shorten the browser width to the mobile view
- Test emoji
- Restore the browser width
- Test emoji (Here the error happens)
