### ISSUE TITLE
Store unread counts in key-value store (Was: Missing DM notifications in Brave)

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1942]
### Problem

It so happened that I had Brave and Firefox open, each with a pinned tab for the GIG group, and got a DM from @corrideat.

I only heard a notification sound from Firefox, and only Firefox showed a number next to @corrideat's name showing I had pending DMs.

I then refreshed the page in Brave, and the next DM that @corrideat sent did result in a notification in both Brave and FIrefox.

You can see the inconsistent count between Brave:

![Screenshot 2024-04-18 at 8 25 04 AM](https://github.com/okTurtles/group-income/assets/138706/ee23813e-8a2b-4ae7-8951-9b2218e1dfa3)

And Firefox:

![Screenshot 2024-04-18 at 8 25 09 AM](https://github.com/okTurtles/group-income/assets/138706/3639c0d9-4d34-4a18-8343-d8f74222f7d5)

Indicating that Brave missed 2 DM notifications.

### Solution

Find out why this happened, and then fix it.

EDIT: store this information in the key-value store, see [this comment below](#issuecomment-2100833715).

**Comment by Silver-IT** [comment]
@taoeffect, I tried to test this issue several times, but didn't encounter this issue. And I'd like to ask a question.
**Did you open Firefox browser first, and then the Brave browser? Especially, after sending two direct messages?**

I would like to point out that the number of unread messages is calculated once the chatroom contract is fully synced. So even if there are unread messages in the browser, they will be zero when the user logs in from the other browser.

**Comment by taoeffect** [comment]
> @taoeffect, I tried to test this issue several times, but didn't encounter this issue. And I'd like to ask a question.
Did you open Firefox browser first, and then the Brave browser?

I had both open at the same time I think.

> Especially, after sending two direct messages?

Not sure what you mean, I didn't send any messages, just received them. I'm pretty sure both browsers were open when the messages came in.

**Comment by Silver-IT** [comment]
@taoeffect, what I mean was that the number of unread messages is calculated after the chatroom contract is fully synced. Let's see the following situations.
- [Tab1] user1 creates a group
- [Tab2] user2 joins the group, and creates a DM with user1
- [Tab2] user2 sends 5 messages to user1 through DM
- [Tab3] user1 logs in
- [Tab2] user2 sends 3 messages to user1 through DM

If we follow these steps, we can see that user1 has 8 unread messages in Tab1, and only 3 unread messages in Tab3. This is because the number of unread messages are not saved in the contract, they are stored in the indexed DB.

So what I wanted to know the time when two browsers were opened in comparison to the time of receiving messages. If the Brave browser was opened after the corrideat sent 2 messages, I don't think the number difference is not an issue.

Actually, I tried several times to see this issue happening, but I couldn't.

**Comment by taoeffect** [comment]
> This is because the number of unread messages are not saved in the contract, they are stored in the indexed DB.

OK, interesting. I agree it shouldn't be saved in the contracts, but I also don't think it should be saved in the local IndexedDB because it will lead to problems like this.

So instead, how about we save it encrypted under the [server's key-value store](https://github.com/okTurtles/group-income/pull/1912) for our identity contract under a `unreadMessagesCount` key?

I've edited the issue title and updated the "Solution" part of this issue to suggest this idea.

**Comment by Silver-IT** [comment]
Yeah, I agree to save it encrypted under the identity contract. But I should think more about the key. I don't think `unreadMessagesCount` would be fine, because there are more to save in KV store. And since we are going to save it to identity contract, I would like to add text `chatRoom` to the key to describe that it's for chatroom.
```
chatRoomLogs: {
  [chatRoomID]: {
    readUntil: { messageHash, createdHeight },
    unreadMessages: [{ messageHash, type, createdHeight, deletedHeight }]
  }
}
```

Let me know if you are fine with this format.

**Comment by taoeffect** [comment]
@Silver-IT Sure, I think. Give it a try and I'll have a closer look when you submit the PR 👍
