### ISSUE TITLE
Cannot access site/PWA on mobile Safari

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#1970]
### Problem

In short, I cannot test the PWA because nothing of substance loads. 

Whenever I visit the URL (both the generic subdomain AND the specific invite link), all I see is a blank page with the GI loading icon. There are no alerts, no dialog boxes, no visible errors, no crashes, no loading bars -- just a white page with small GI loading icon. (When phone is in dark/night mode, the page background is properly dark instead of white.)

I've made sure iOS is up-to-date and also restarted the phone. I've tried multiple networks. I've tried with a second device that's never been logged into the app before. This happens in regular Safari on iOS and also when I try via PWA. 
Edit: This also happens on Brave on iOS.

![IMG_7646](https://github.com/okTurtles/group-income/assets/13082264/0ca7864e-9291-4ff6-ba4a-8fd3391a84b3)

![IMG_7645](https://github.com/okTurtles/group-income/assets/13082264/1da20fd6-bf57-4aad-9931-462915561399)

### Solution

Determine why the PWA (and site) won't load, and fix it.

**Comment by taoeffect** [comment]
The console error that I get on an old iPhone SE is:

> SyntaxError: Invalid regular expression: invalid group specifier name

No line number is given, but based on a search we see this: https://developer.apple.com/forums/thread/676852

Where they had a line like this:

```js
const re = /(?<=\()([^)]+)(?=\))/g;
```

This is valid code, and the reason they got this error is because it uses [lookbehind regex](https://caniuse.com/js-regexp-lookbehind), which wasn't introduced until iOS 16, and old iPhones cannot run iOS 16.

So closing this as "wontfix" since we really should only support browsers that support regex lookbehind, and this phone is no longer supported even by Apple and is vulnerable to various security problems.
