### ISSUE TITLE
Show all (important) notifications on all devices/browsers

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#1992]
### Problem

When viewing notifications on a second device/browser, not all notifications are shown. All important notifications should be shown on all devices/browsers so users don't miss any. 

In the screenshots below, you can see for example that both proposal-related notifications are missing on the second device/browser
(and also that the read status is per-device/browser, which is issue #1936 )
<img width="459" alt="Screen Shot 2024-05-11 at 11 27 10 PM" src="https://github.com/okTurtles/group-income/assets/13082264/73472bab-4fff-4029-b227-c692f7015931">

<img width="461" alt="Screen Shot 2024-05-11 at 11 27 17 PM" src="https://github.com/okTurtles/group-income/assets/13082264/c00afc1f-658c-4c36-9e79-8914d9d5b24c">

### Solution

It is fine to show all notifications and have them be identical on all devices/browsers.
If not all notifications are synced, then important notifications should be shown on all devices. At minimum, "important" notifications should be ALL unread notifications and the most recent notification of each type (e.g. the most recent mincome change, the most recent notification that User X has joined, the most recent period reminder).

**Comment by Silver-IT** [comment]
While I was working on this issue, I tried to the joining/leaving group several times to encounter the issue described above.
But I saw the weird dashboard. 😲 😱 No navigation bar...
![image](https://github.com/okTurtles/group-income/assets/57976479/68e1da2d-8fac-44f8-8f4c-893180b4d7ce)

I tried to logout and login again but could not see the navigation bar.

**Comment by Silver-IT** [comment]
Also, even though user has already been kicked from the group, but he is still inside the dashboard page.
With no navigation bar.
![image](https://github.com/okTurtles/group-income/assets/57976479/594426ad-ea5e-4347-9dd7-87c9cf60b43e)

Steps to reproduce
- [Tab1] user1 signs up and creates a group
- [Tab2] user2 joins the group
- [Tab3] user3 joins the group
- [Tab1] user2 kicks user3
- [Tab3] user3 gets the screen above

**Comment by Silver-IT** [comment]
Having tested this issue several times, I think the original issue is already fixed. I guess in the PR #1986.
Regarding the read status problem, we have a separate issue for that so I think we should work on the Issue #1936.
@dotmacro, can you please try to test this issue and let me know if you still encounter missing notifications problem?

But as I have already reported in here, joining/leaving group is not yet stable and not working well. I will try testing more and create a independent issue for joining/leaving group with minimal steps to reproduce.

cc: @taoeffect, @corrideat 

EDITED: Since the Issue #2032 is related to the joining group process, I will add the encountered issues there.

**Comment by dotmacro** [comment]
I was also unable to recreate this issue, so hopefully was already fixed. Thanks for investigating! 

Will update & re-open if I notice this issue again.
