### ISSUE TITLE
retina display support for assets

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2]
## Problem

People use radically different resolution displays, and assets that look good on one don't look good on the other.
## Solution
- https://imulus.github.io/retinajs/
- resolution independent formats like svg

**Comment by sandrina-p** [comment]
SVG solution related to https://github.com/okTurtles/group-income-simple/issues/101

**Comment by sandrina-p** [comment]
Let me bump this up!

### Problem
Our current strategy is using inline SVGs that handle perfectly this issue.
Now the new challenge is that we need to support animations and different colors based on the theme, so the SVG needs to be used inline, which causes some noise in the code because of its massive length.

### Solution
We need to implement a more elegant solution. By using `<use/>` and sprites technique with `<symbol />`. You can read more about it [here](https://css-tricks.com/svg-symbol-good-choice-icons/) and [here](https://css-tricks.com/svg-sprites-use-better-icon-fonts/). It's not a hard/long task and once done automatically supports all the future SVGs. 

cc @pieer

**Comment by mmbotelho** [comment]
Just to add to what @sandrina-p said - the only place we might have a problem with pixel density is the user avatars and, possibly, images uploaded in the chat.
