### ISSUE TITLE
Allow creation of DM with yourself

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2002]
### Problem

It is very useful to be able to create a DM with yourself to share and remember notes with yourself.

Right now we can't do this because the DM creation modal doesn't show your username in it.

### Solution

- Allow creating a DM to yourself.
- If a DM is created between you and some other people, treat it the same way as we do right now with creating a DM with those other people (just ignore the fact that you're also listed in the DM - you are obviously are going to be part of the conversation).

**Comment by SebinSong** [comment]
Hi @taoeffect ,
As a solution for this issue, how would you like that we add `To: @Me` button underneath the search bar, instead of showing the current user in the "Others" list below? (I feel this can be a solution that brings the least amount of complexity to the existing logic and can make the feature stand out to the users at the same time)

![image](https://github.com/user-attachments/assets/54116f28-07ce-4e10-be81-932317cd24c4)

**Comment by taoeffect** [comment]
@SebinSong No, I'm not a fan of complicating the UI. I am a fan of simplifying the UI. If, for example, you prefer to get rid of "Recent Conversations" and "Others" and just have a list of users (and convos?) in the list, that works too.

My preference would be to treat your user as anyone else.

**Comment by SebinSong** [comment]
@taoeffect 
> My preference would be to treat your user as anyone else.

Got it!

**Comment by SebinSong** [comment]
@taoeffect 
Below is the welcome message printed after a DM is created. What would you like it to say for the case of DM to myself?

<img src='https://github.com/user-attachments/assets/90c7d452-f978-44c4-a937-de62ac823b0f' width='430'>

**Comment by taoeffect** [comment]
Good question! How about: `You can post private notes to yourself here.`
