### ISSUE TITLE
Cypress heisenbug on Contributions page for non-monetary contributions entry

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2003]
### Problem

This recent merged failed: https://cloud.cypress.io/projects/q6whky/runs/2274/test-results/0e748179-23f6-4916-b3ed-f97c863b32c7

### Solution

The problem appears to be related related to some UI issues with Vue and the non-monetary contributions page.

Figure out what the issue is and fix it.

**Comment by Silver-IT** [comment]
@taoeffect, having investigated the PR #1999 (since the Cypress fail is from that PR), I can see there is no regarding non-monetary contributions related updates.
And also having tested the current `master` branch several times, Cypress doesn't fail in my local.

Should we think it's a kind of heisenbug?

**Comment by taoeffect** [comment]
On Slack @Silver-IT said he thinks this is no longer an issue. Sure we can close this but if we see it again we should re-open this issue.
