### ISSUE TITLE
Set reasonable character limits for payment info

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2112]
### Problem

The text boxes on the payment info screen seem to accept an unlimited number of characters. (For reference, I gave up after 524,288 chars in 97,967 separate words.) Among other issues, this pushes the top of the unscrollable user info card off the top of the screen, hiding the profile photo, username, and any payment info that's higher in the list. 

<img width="408" alt="paymentInfoNoCharLimit" src="https://github.com/okTurtles/group-income/assets/13082264/8ef51f3e-8973-4e30-9910-c5d75a34ed4a">

### Solution

Limit the input to 250 characters. 
Indicate the user has reached the char limit the same way we do with usernames and group descriptions: an error with the text "Payment info cannot exceed 250 characters."

**Comment by Silver-IT** [comment]
@dotmacro, once we set the `maxlength` in the Input element of each payment method, it doesn't allow more than `maxlength` number of characters. So, no error message needed I think.
So two options;
- Allow users to type more than 250 characters. And if exceed, show error message.
- Do not allow users to type more than 250 characters

Which one do you prefer? (I also check how we handle group description, and it doesn't allow 500 characters, and do not display any error message)

cc: @taoeffect

**Comment by taoeffect** [comment]
@Silver-IT 

> Do not allow users to type more than 250 characters

I prefer this option 👆

EDIT: but remember that hackers can bypass the UI restrictions, so when fixing this please make sure to also add a check to the `validate:` part of the contract, as that will prevent malformed messages from being sent and processed.

**Comment by dotmacro** [comment]
> I also check how we handle group description, and it doesn't allow 500 characters, and do not display any error message

That was #2077 , which should have been fixed by #2084.

Users absolutely should be told why they cannot type any more characters (or why an input cannot be submitted, or etc). 

And behavior should be consistent across the app. Indicate the user has reached the char limit the same way we do elsewhere: an error with the text "Payment info cannot exceed 250 characters."

**Comment by taoeffect** [comment]
> Users absolutely should be told why they cannot type any more characters (or why an input cannot be submitted, or etc).

~~I disagree. Instead of letting the user type more than 250 characters, and then giving them an error when they try to submit, we should just enforce a hard limit of 250 characters.~~

*EDIT: Actually, the point that this could (theoretically) cut off important payment information that was pasted without the user knowing is a good point. So yeah, maybe we should allow them to paste as much as they like and then show an error message to prevent submitting the form.*

On large fields where there is room to show a counter (like the group description field, or the user profile field), it's fine to add a counter (e.g. `10/250`).

But here on these small input fields we should just limit the length with a hard limit.

The alternative would be to add a large amount of sophisticated code that we don't have time to implement to make it more like X/Twitter does it, where it turns the text background red after the limit is reached. But we just don't have time for that right now.

**Comment by taoeffect** [comment]
@Silver-IT I've changed my mind, having been persuaded that it's better for these fields to let users exceed the limit and show an error using the existing error feature instead:

![image](https://github.com/okTurtles/group-income/assets/138706/759286c6-816c-4fb0-a214-086b44fef772)

Copying edit from above:

> EDIT: Actually, the point that this could (theoretically) cut off important payment information that was pasted without the user knowing is a good point. So yeah, maybe we should allow them to paste as much as they like and then show an error message to prevent submitting the form.

**Comment by taoeffect** [comment]
@Silver-IT this is also fine (this is how we do it for the Sign Up form):

![Screenshot 2024-07-04 at 7 38 31 PM](https://github.com/okTurtles/group-income/assets/138706/e205c578-77b8-462d-b55f-7b0399a7895d)

**Comment by Silver-IT** [comment]
Make sense. That's a really good point that the payment info could be cut off when the users paste it. I will update the PR soon.
