### ISSUE TITLE
Chatrooms not loading on testing site

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2119]
### Problem

Switching to some chatrooms results in an error and the messages do not load:

![Screenshot 2024-06-25 at 11 59 04 AM](https://github.com/okTurtles/group-income/assets/138706/3f886163-9662-4217-ab0a-fc768c7f901f)

![Screenshot 2024-06-25 at 11 58 55 AM](https://github.com/okTurtles/group-income/assets/138706/0f34aaac-509b-416d-b5ba-8f25d5b60149)

![Screenshot 2024-06-25 at 12 04 23 PM](https://github.com/okTurtles/group-income/assets/138706/4ed2f951-3d49-4684-b113-6488734b1ef4)

Sometimes it does load, and sometimes it doesn't. Usually it doesn't..?

This seems to happen specifically with private chatrooms.

### Solution

Find out what the problem is and fix it.

**Comment by corrideat** [comment]
This seems to happen because the value stored in `currentChatRoomReadUntil` refers to an event ID that doesn't exist, which causes the call to `eventsBetween` to fail as shown.

As for why the event doesn't exist, it could be related to unsent (pending) messages, as those have not necessarily been posted to the server, and their ID might change once they are sent. In combination with #2061, this issue makes sense.

If this is the reason, the solution would be not to store unsent messages in `currentChatRoomReadUntil`.
