### ISSUE TITLE
Require non-monetary contributions for those making less than mincome

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2245]
### Problem

If people who are receiving monetary income do not add non-monetary pledges, then this can be both bad for the monetary receivers and pledgers as the pledgers may start to feel taken advantage of, and the receivers may start to feel like they aren't contributing anything.

### Solution

Avoid this problem by requiring at least 1 non-monetary pledge in the income details screen for monetary receivers.

This is both a design and implementation issue. @dotmacro said she'd work on the design.

**Comment by dotmacro** [comment]
Design for those making monetary pledges: 

![image](https://github.com/user-attachments/assets/20ec3bb5-d413-4f78-8fa1-461ddf7490a5)

Note: The non-monetary pledge is optional, but that section is otherwise identical as for users who aren't making monetary pledges.
Figma link: https://www.figma.com/design/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=27201-32141&t=PrnaOWxXXZgn7U6a-1 


Design for those not making monetary pledges: 

![image](https://github.com/user-attachments/assets/9b2bfe2b-dcff-4dae-83fc-f4eb950f72a9)

Figma link: https://www.figma.com/design/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=27201-31346&t=PrnaOWxXXZgn7U6a-1
