### ISSUE TITLE
Implement search functionality for payments

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2296]
### Problem

On `testing` and `live`, the "Completed" tab on the "Payments" view shows a search box and a loupe icon. The user can type text into the search box, but there is no way to submit the query -- neither clicking the icon nor hitting the enter key does anything. Search is not implemented. 

![search](https://github.com/user-attachments/assets/5e823897-ebfa-4e47-9b5a-39a366d4f025)

### Solution

Implement this search function. (In the meantime, hide the non-functional search box and loope from the UI.)

**Comment by SebinSong** [comment]
@dotmacro 
I just investigated this issue and it looks like the search function is implemented but currently broken due to this run-time error.

<img src='https://github.com/user-attachments/assets/fe3265dc-2708-4efb-8114-f450dcadd7e3' width='480'>

FYI, the search is executed for each keystroke not by any call-to-action.
