### ISSUE TITLE
Add Flow support to .vue files

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#273]
### Problem

Our static analyzer currently doesn't analyze the JS in .vue components, this can lead to bugs not being caught.

### Solution

[Writing Vue.js Components with Flow](https://alligator.io/vuejs/components-flow/)

**Comment by snowteamer** [comment]
This solution unfortunately requires many dependencies.

That being said, we are currently already using all of them except `eslint-plugin-flowtype-errors`. It could still make them harder to remove in the future, though.

I also noticed this issue was not closed because `npm run flow` would still not report Flow errors in .vue files.

Indeed the above solution doesn't enhance `flow` with new functionality, but rather enables ESLint to run it on .vue file script contents and report the results. Therefore it requires running `eslint`, which `npm run flow` currently doesn't, although it should be easy to patch.

However I'm a bit concerned about increased build times if this feature was enabled by default, since .vue files are linted at build time. Calling `flow` repeatedly for each .vue file is likely very slow, especially in presence of many errors. So it might be better to enable it only in the context of `npm run flow` for now.

**Comment by snowteamer** [comment]
Another difficulty regarding this issue is that our new build system should be updated to accept Flowtype syntax in Vue components. This would likely require patching our esbuild Vue plugin to remove Flowtype code during the compilation process.

**Comment by taoeffect** [comment]
> Calling flow repeatedly for each .vue file is likely very slow, especially in presence of many errors. So it might be better to enable it only in the context of npm run flow for now.

I agree - only makes sense to do it on first run of `grunt dev` along with `npm run flow`, but not on re-build.
