### ISSUE TITLE
Create a whitepaper, max 9 pages

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#293]
### Problem

Group Income has a blog, has an FAQ, has a bunch of short videos, but is missing more detailed documentation, and this includes (but is not limited to) the lack of a whitepaper.

### Solution

Write up a whitepaper. Cannot be longer than 9 pages.

**Comment by dotmacro** [comment]
I drafted some docs at the hackathon that may help. Most are for the FAQ, but at least one of them is closer to whitepaper-style.

Haven't added them here, since they're work-in-progress for the website (which is no longer using [its repo](https://github.com/okTurtles/groupincome.org)). Would you like me to email them, add them to /docs, etc?

**Comment by taoeffect** [comment]
> Haven't added them here, since they're work-in-progress for the website (which is no longer using its repo). Would you like me to email them, add them to /docs, etc?

Can you put them into our existing Git*Lab* wiki or create a new Git*Lab* project for them?

**Comment by dotmacro** [comment]
Certainly! 👍

**Comment by taoeffect** [comment]
Stale #456
