### ISSUE TITLE
Improve Development Flow

### ISSUE THREAD

**Issue by ktamas77** [okTurtles/group-income#307]
### Problem

The current development Flow is very time consuming, mainly because of two reasons:
* `grunt dev` and `grunt test` cannot be run in the same time. This requires the developer to restart the dev server between each tests which leads to tremendous loss of time
* `grunt test` right now spews out a lots of noise to the console. the output should be clean, it should show only the tests statuses, and in case if any test is broken, show context only for the broken test.
* Data loss - the database is not persistent between test / development cycles.
* Performance - the build process should be more efficient.

### Solution
* Run a test in the development environment in `grunt dev_test` mode when the user is making a change.
* The test should always use it's own, separate database to avoid data corruption in the development database.
* Add `Watchify` or similar a tool. Evaluate multiple similar solutions in order to find the best. This should speed up the test/build cycles between each change during development.

**Comment by taoeffect** [comment]
It might make sense to at some point add `watchify` support, that's already an open issue (#274).

Making the tests parallelizable with `beforeAll` etc to create multiple instances of Nightmare might also make sense if that's possible. We can then use one of the Mocha parallelizable plugin things ([mocha.parallel](https://github.com/danielstjules/mocha.parallel) or [mocha-parallel-tests](https://github.com/yandex/mocha-parallel-tests)) if the latest version of Mocha doesn't support parallel tests by itself, or [ava](https://github.com/avajs/ava), but that would require rewriting more parts of our test code.

The `grunt dev_test` command, OTOH, I don't think is worth spending time on, only because it's very rare when someone would want to run a test on each save. I don't see much value in that, and since developers save frequently there's a high probability of breaking the existing running test.

**Comment by sandrina-p** [comment]
I agree with @ktamas77 . If we want to have solid tests, one of requirements should be to have a flowless dev experience doing this.

I've also noticed we are using an old mocha version (3) and it's already on 5.

**Comment by taoeffect** [comment]
We've updated to mocha 5, and running `grunt dev` and `grunt test` at the same time doesn't make sense so I'm closing this old issue for now.
