### ISSUE TITLE
Update docs to remove Mileposts stuff

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#363]
### Problem

So far at least, nobody has actually used the Mileposts methodology, including myself. It just doesn't seem necessary, as we can use the [Projects](https://github.com/okTurtles/group-income-simple/projects) page (and chat) to coordinate instead.

### Solution

- Remove Mileposts mentions from `README.md`, `CONTRIBUTING.md`, and any other docs
- Remove the Mileposts label, and convert / close / update any Milepost issues as appropriate

**Comment by taoeffect** [comment]
Here's [an interesting blog post](https://hackernoon.com/the-effective-tech-lead-is-a-100x-engineer-fe49c0372a63) talking about a  **"Master Tracking Issue"**, which sounds suspiciously similar to my [Mileposts methodology](https://github.com/taoeffect/mileposts).

I leave this here in case either of you, @sandrina-p or @hubudibu, decide that Mileposts are in fact something that we should try after all, or whether we should continue as we have so far.

I honestly don't know what's best. I've merely observed we haven't needed them up to this point, but with more people on board perhaps they might end up coming in handy after all.

I ask that both of you (and anyone else contributing to this project) please keep communication lines open with me and tell me **what will make life easier for you**. Am I screwing anything up? Can I be better about responding to your questions and pull requests? Is there some documentation you think I should write? Is there some service or tool that would make your lives easier and your work better?

My job as project lead is not only to contribute code occasionally, it is primarily to serve you — the developers and designers — and help you with any problems you're bound to encounter. So tell me, either on Slack in `#groupincome` or Keybase or via DM or whatever you prefer.

**Comment by sandrina-p** [comment]
This is a hot topic - decide work/tracking/productivity methodologies.
Regardless the methodology we use (mileposts / agile / etc... ), I believe our concern is the same:

#### What's our team main goal
Release _Group Income Simple Beta_ (Am I correct?)

#### What's our roadmap (Milestones to accomplish the main goal)
I don't know :x

#### What's our focus in each Sprint (sprint = 1 week)
I only know mine (onboarding duh) but I'm not sure about yours. Using Projects, as @hubudibu shown us, is definitely a way of clarify that.

#### How each task is organized / What's the process
Having issues  for each task + labels is a great way to see what needs to be done, but I don't understand what's our focus / process, so I believe we need a tool that helps to _get shit done_.
There are a lot out there (trello, jira, motion, you name it...) but **I believe Github Projects suit us perfectly** because is automatically integrated with Github (native tool/feature).

My suggestion is, based on my experience and seeing how other open-source remote teams works is:

Have a project per Sprint with the following columns:
- To do
- In development
- Code Review
- Done
- (any other column it might appear ex: discoped, blocked, etc... )

I also suggest a "Design" project, since the process can be a little different from dev.
- Research / Inspiration
- Priorities
- In progress (should have the same tasks as the respective "Sprint" board)
- Done



What I like the most about this kind of way to track our work (Projects) is the flexibility it has to adapt to our needs as we evolve. Whatever tool we choose I believe the most important thing is to stay focused and motivated.

What do you guys think?

**Comment by hubudibu** [comment]
I completely agree that making our goal more explicit and clarifying our focus on an ongoing basis is beneficial. it doesn't just make the onboarding easier, it helps to stay focused and motivated, as @sandrina-p put it 👍 This is what I wanted to trigger with my project board suggestion, I'm glad it worked :)

I would push for going with the minimal solution here - as well as in our PRs. I would suggest extending the project board that I started with any new column or functionality that you feel are missing. and I would love to have the same board for design and development, and see the whole team's progress in one space! for the slight process differences, here goes my suggestion:

- backlog
- priorities
- in progress
- review
- done 

I updated the columns in the project board and encourage you too to do so.

for the weekly sprint boards: what would be the benefit for having a new board for each week in our current state?

**Comment by hubudibu** [comment]
ah, and for research/inspiration, I would suggest using the wiki once you get access, that's a great place to flood with ideas!

**Comment by sandrina-p** [comment]
@hubudibu I agree with you, let's keep it as simple as possible. For now one board should be enough! 
 Then when things start to get out of hand we adjust our board(s)!

@taoeffect do you have anything else to say or can we close this issue?

**Comment by hubudibu** [comment]
about the mileposts question: a related problem that I ran into is that right now it is quite hard to say where we are with the project. what is the desired feature set for the prototype? where are we with each feature? for most of this, we have issues open, but it is hard to tell feature issues from improvement ideas, and not all missing or buggy features are covered with issues. my need here would be a feature list with statuses, mileposts could be a solution for this, but anything simpler would already help a lot

**Comment by taoeffect** [comment]
@hubudibu Yes, it sounds like we're going to try going with your suggestion and use boards for now instead of Mileposts

> can we close this issue?

Well, as soon as we remove mentions of Mileposts from the documentation this issue can be closed, or unless we've decided we actually want to keep them around.

If we're just sticking with the project boards for now I can submit a PR to close this issue, although it's also possible I might get distracted by other higher priority tasks! 😅

**Comment by sandrina-p** [comment]
I wouldn't remove Mileposts right away until we polish the way we use Projects. I suggest we keep this open and in 1 month we review how this  "Projects flow" went out!
