### ISSUE TITLE
Information Architecture

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#369]
### Problem

Following the discussion https://github.com/okTurtles/group-income-simple/issues/363#issuecomment-377567744 about the lack of progress / focus
>(...) it is quite hard to say where we are with the project. what is the desired feature set for the prototype? where are we with each feature? 

I believe our current problem won't be solved only by using _Github's Projects_. That's a good way to focus on a small amount of pieces of a bigger puzzle, but we would still miss what's the final puzzle will look like. I speak for myself right now, I didn't understand yet well what are GIS features and what's missing (or what you guys have in mind).

### Solution

Here's where a Information Architecture (IA) comes into place.

> Just like a blueprint, IA provides designers (as well as product development and engineering teams) a bird’s-eye view of the entire product. Having a single document that delivers a simple and understandable representation of how the application or website works is vital for developing new features, updating existing ones, and for seeing what is possible considering the existing product. 
> \- [_A comprehensive guide to information architecture_](https://blog.prototypr.io/the-comprehensive-guide-to-information-architecture-29b09695fbcb)

An IA is like a map of all views / journeys / features the user can perform on a specific product. Personally I use IA to remind me of all the things I can't picture directly. Almost like _"just because you can't see it, doesn't mean it isn't there"_. 

So, based on my journey through the current GIS App I've ~~started GIS App IA~~ created a [GitLab wiki's page - Information Architecture](https://gitlab.okturtles.org/okturtles/group-income-simple/wikis/Information-Architecture) Please take a look and let me know if you think it can better answer the following @hubudibu initial questions:
- where we are with the project.
- what is the desired feature set for the prototype?
- where are we with each feature? 

IA files are meant to evolve as we progress and help us to make decisions and better know what are the next steps while we can have a picture of what's missing to reach our final goal.

The IA I've created is based on a user's perspective of the product. A similar IA can also be done to better organize backend stuff.

**Comment by hubudibu** [comment]
👍👍👍 I love this direction!  
I used to have a similar architecture set up on my desk with post-its, but this is definitely more useful on the team level :)   
for the tool used, to be a better decentralization citizen, is there any alternative that can eventually be self-hosted, or at least doesn't depend on Google's infrastructure? this might be a bit more painful to maintain, and seems less powerful, but GitLab supports mermaid in markdown files: https://docs.gitlab.com/ee/user/markdown.html#mermaid so we could keep this architecture diagram in our wiki for example

**Comment by sandrina-p** [comment]
Wow, I took a look into [mermaid docs](https://mermaidjs.github.io/) and I think it can do a lot, even roadmap graphs (see gantt diagram section). We can integrate it [on a project](https://mermaidjs.github.io/usage.html) so we have more power over it with js and styles. It doesn't seem rocket science to understand the syntax and the docs are great.
We could start it simple on wiki yes, and if thing get complex we move on to html.

(I'll be trying it during the next hours. I'll ping you back when I have something)

**Comment by sandrina-p** [comment]
@hubudibu After 2h trying my best with mermaid and at the same time keep things simple, I came with [this Gitlab's wiki page](https://gitlab.okturtles.org/okturtles/group-income-simple/wikis/Information-Architecture) What do you think? 😶

**Comment by taoeffect** [comment]
I really like this, at the very least I think the wiki you created looks great, and can potentially be a very useful thing in the future, especially for on-boarding new people and verifying our own thinking.

However, I will raise the following concerns/warnings about getting too heavily into this *at this point in time*:

- It is often a huge pain just to keep comments above code in sync with what the code actually does — and so I suspect it will be a similar pain to keep documentation in sync with the reality of the app
- It is easy to get carried away with planning, diagramming, and doing everything possible *except for actually writing code*

I want to stress that and warn against it. In my experience, there is no better teacher than the code itself. There is no better way to learn about a project than diving straight in and experimenting with the code yourself.

So while this is interesting and potentially quite useful, it will be faster to just dive straight into the code of the dashboard and forget about everything else. As you do I am willing to bet that everything will become much clearer and self-explanatory. Any questions that remain — well, that's why we have a chat channel where you can ask them, and video chats, etc. :)

Also, since @hubudibu was the one who asked the original three questions, I think they deserve a direct answer from me.

> - where we are with the project.

We are readying the prototype.

> - what is the desired feature set for the prototype?

- Create / join group (done)
- Dashboard display (@sandrina-p can tell us where we are with that)
- Basic payments system (that is my and @ktamas77's responsibility, so don't worry about it for now unless you think you need to)
- A good, functional UI that works in all major browsers and isn't clunky
- User registration with password that works (my job, so don't worry about it)
- A fully functional proposals system (@hubudibu's code, with help from @sandrina-p for the UI/UX)
- A coherent notification/error display and logging system
- A basic user chat and mailbox system (mostly done, some of it needs re-work, and the UI/UX needs an overhaul from @sandrina-p)
- A fault-taulerant transaction system (@hubudibu is working on this right now)
- A bunch of "core plumbing" features to support all of the above (mostly done, but some of it remains to be written, and some of it needs to be rewritten. These are the `Kind:Core` tasks, most are my responsibility, with potential help from @hubudibu's)

> - where are we with each feature? 

I've given a gist of that above.

So that didn't take long. Now let's dive deep into the work and forget all meta-work.

**Comment by sandrina-p** [comment]
I'm sorry if I took too much time into trying to make things more intuitive. That was my way to better visualize how GIS is organized and what's missing from the user's point of view, so I can do a better job when focusing on the Dashboard display task.

Besides that, thank you for your answers to @hubudibu questions, special the bullet list.

**Comment by taoeffect** [comment]
No worries at all, it's a good idea and definitely useful for onboarding purposes. Right now we don't have a high need to onboard lots of new developers though, and you have a much faster more efficient way of getting all of the info you need, which is directly messaging me or @hubudibu. I'm happy to jump on a call any time I'm around, just shoot me a message and I'll do my best to make myself available to you ^_^

**Comment by hubudibu** [comment]
both the architecture diagram and the bulleted feature list are super helpful for me as well to stay focused and not get lost in the details, thank you guys! 🙏

**Comment by taoeffect** [comment]
I think this can now be closed, right? Feel free to re-open if not so!
