### ISSUE TITLE
Copy Bulma into a folder and trim it down to bare essentials

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#392]
### Problem

- Bulma has more features than we need, increasing page load times and increasing the bundle size
- Bulma introduces breaking changes frequently
- Bulma is another dependency (#372)
- Bulma might do some things in ways that we don't want (for example, we might want to switch away from SASS/SCSS to PostCSS, or some other thing; @sandrina-p probably has ideas)

### Solution

Copy only the files from Bulma that we need into our a subfolder within this project and remove Bulma as a dependency, without changing it too radically so that we can no longer port over new Bulma features.

**Comment by sandrina-p** [comment]
Switching from SCSS to PostCSS is a solution, but that isn't done in a row. It has to be a thoughtful migration, since Bulma is 100% built in SCSS. At first we can have both working at the same time, since PostCSS has features that SCSS doesn't have (ex: fallback for CSS variables).

Subfolder for Bulma can be the current `/bulma_overrides`.

**Comment by taoeffect** [comment]
Closed in #573
