### ISSUE TITLE
Make pressing <Enter> key work in various places

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#401]
### Problem

Pressing enter should work properly when inviting members (#312), when creating a group (e.g. typing in the group's name, then hitting enter/return, should work).

### Solution

Currently it doesn't.

**Comment by simonv3** [comment]
I think I need some elaboration on this ticket: 

Pressing enter when entering a group's proposed name seems to work. 
It doesn't work for the group's purpose, but that's a `textarea` element so that makes sense to me. 
It seems to work for entering an amount.
It works when I type in an existing user's name and press enter, the user pops up with an icon: 
![screenshot from 2018-11-27 19-33-18](https://user-images.githubusercontent.com/485583/49127206-5245b780-f27b-11e8-8bcb-8b185e35e449.png) but it doesn't work to have enter press next. Is this the intended UX here? It also works in the invite users page through the proposals. 

Maybe this was closed by the work done for #312? Or am I missing something?

**Comment by taoeffect** [comment]
Yep, this was closed!
