### ISSUE TITLE
Doesn't return to dashboard after member has been invited

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#404]
### Problem

1. In one window, create a new user A and group
2. In an incognito window, create a new user B
3. In the first window, in the dashboard, click the + button to invite B to join the group

It will say "Members invited successfully!" but instead of redirecting to the dashboard it just shows a "Send Invites" button, which can be clicked again a bunch of times, which is also a bug.

![screen shot 2018-05-13 at 11 29 32 pm](https://user-images.githubusercontent.com/138706/39977146-d8042a4e-5705-11e8-97f7-17525a5fce29.jpg)

### Solution

- After inviting a new member(s), it needs to redirect back to the dashboard, or even better, close the invite modal (which currently doesn't exist but needs to)
- You definitely shouldn't be able to invite the same users multiple times, that should be an error.
- Add a test to catch this next time

**Comment by simonv3** [comment]
This seems like a good next issue for me.

**Comment by simonv3** [comment]
I feel like to do this properly we need something in place for #175. I can work around that for now though?

**Comment by taoeffect** [comment]
@simonv3 well to fix the main issues here I don't think it needs anything re the notifications, unless I'm misunderstanding you? However yes the notifications are something that we need to start working on soon, and that's also something we need @mmbotelho's help with in terms of design (when she gets back).

**Comment by simonv3** [comment]
Just to clarify:

Currently what the functionality does (and tests expect) is to show a notification upon success. This notification is handled internally to the Invite component and is displayed there. When automatically redirecting the invite component that notification is lost (because the Invite component closes), and there's no feedback on the Group's dashboard that the invites were successfully sent. So my understanding is that either

a) we wait until global notifications are set up that we use to handle the notification #175 
b) we use an invitees component on the dashboard to convey this information to the user
c) we send success confirmation to the dashboard through some other means, and have the dashboard handle this specific notification on its own (though I feel like at that point we should just do (a) or
c) we don't display any kind of confirmation
d) we don't redirect the user and change to "Invite" component to be a kind of status page for invitations.

A or B sound the best for me, and honestly I think we should do both either. So I'm going to hold off continuing working on this ticket until either (a) is implemented or (b) is designed (cc @mmbotelho). 

Temporary work for this can be seen here, and the changes there should also help explain some of the conflicts I described above: 

https://github.com/okTurtles/group-income-simple/compare/master...simonv3:task/404-redirect?expand=1

**Comment by taoeffect** [comment]
Yeah I think having a component of pending invites to the group on the dashboard is a good idea. How that's done will require some thought. It could be a box, or something less obtrusive and as simple as text that says "2 invites pending", that when you hover over shows a list of names via tooltip, and when clicked on brings up a modal that lists the invites.

**Comment by simonv3** [comment]
I've created a ticket for it here: https://github.com/okTurtles/group-income-simple/issues/510

**Comment by sandrina-p** [comment]
I believe we can close this issue because it's a duplicated / stale bug. Implementing correctly the new Invite User journey is addressed at #553

**Comment by taoeffect** [comment]
I'm going to re-open it because [this comment says that PR 655 should solve the issue](https://github.com/okTurtles/group-income-simple/issues/553#issuecomment-528947379), but it didn't.

**Comment by sandrina-p** [comment]
Hum... I have a different understanding of it.

> PR #655 should solve this issue

I think @mmbotelho said that #655 should solve #553.

And I said in the previous comment that #553 will solve this current issue (#404) , which means, it will handle the redirect correctly.

Actually, in the current user journey (as in designs 2.0 - to be implemented), there's no redirect because it's a modal, so this current issue doesn't make sense anymore, that's why I said it's stale and I've closed it.

I'm not sure if I was clear enough... this makes me think we have some opened issues that are very similar or overlapping each other and it creates extra noise.

**Comment by taoeffect** [comment]
@sandrina-p I see what you mean now, OK, fair enough. I can close this in favor of #553.
