### ISSUE TITLE
Use Vue Test Utils for unit testing .vue files

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#421]
### Problem

As @sandrina-p points out, we currently only do integration tests on .vue files, which can be slow when integration tests aren't necessary for some of the tests.

### Solution

Explore using Vue Test Utils and possibly switching from Mocha to Jest (if it is necessary, but I'm not clear on that or what the pros/cons of Mocha vs. Jest are).

- https://vuejs.org/v2/cookbook/unit-testing-vue-components.html
- https://vue-test-utils.vuejs.org

**Comment by sandrina-p** [comment]
I've never used Mocha, so I can talk about it directly. But these are the Jest pros I've seen so far:
- Configuration is really minimal compared to any other test runner.
- It has snapshots! (made for React but there's support for Vue too!)
- Mocks are really powerful and easy to do.
- It comes with `--watch` that speed up my development.
- It comes with code coverage reports which help me while testing a unit.

If you look out on the Internet, Jest is getting a lot of attention and support, and besides that is a tool I feel very comfortable with.

**Comment by sandrina-p** [comment]
Based on our journey so far, we have done well with e2e tests to cover frontend functionality and I think we are in the good path. For that reason, I believe we can close this issue mostly because we have been [writing tests, not too many. Mostly integration](https://kentcdodds.com/blog/write-tests) and that’s fine for the prototype!

 Feel free to reopen it if you believe we should also add unit testing to Vue.
