### ISSUE TITLE
Navigation: Beyond headers and sidebars

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#435]
### Problem

![image](https://user-images.githubusercontent.com/14869087/42181719-c0d0d732-7e33-11e8-8547-4cf52fa57093.png)

Currently GI has two kind of navigations with some actions:
- Header
  - GI Logo: Goes to current selected group dashboard
  - Pay Group: I suppose this link goes to a different page depending on the current group selected.
  - Groups: Does exactly the same as the "logo" link
  - Inbox: Area to communicate any important event. Notifications and messages at the moment. Currently we are not sure how this should work (that's another different issue)
  - Profile: A single profile that is common to all groups the user belongs to.
- Sidebar on Dashboard
  - List of groups the user belongs to with possibility to create a new one.

### Solution - (Questions actually)

I explored how "Group Apps" similar to ours solve these problems in order to learn from them, so we can improve GI workflow.

ATM the current navigation doesn't reflect a solid workflow and based on how the user interacts with Groups, will dictate how the navigation should be designed. So, I believe @taoeffect can better answer (or predict an answer) how users will behave, so we can take better decisions to improve the Navigation.

1. Can the user have a different Profile for different groups or it's a common profile for everyone?
2. What do you think it will be the average number of groups a user belongs too?
3. What's your vision/plan for "Pay Group" area?
4. ATM a group only has "threshold" settings. In the future, will be possible to to also change name / description or even arrange "widgets" order? Only the group admin can do it, correctly? If so, should we also have an area to manage the member "roles"?
5. Is anything for the Prototype that we didn't started to develop yet? Something that is completely out of the UI, like removing a member for a group?

**Comment by taoeffect** [comment]
> Can the user have a different Profile for different groups or it's a common profile for everyone?

Usernames are registered in a namespace that is global across groups.

> What do you think it will be the average number of groups a user belongs too?

I honestly do not know. At first it will be just 1, but as the app evolves with new features it could grow beyond that. For version 1 however, it will likely be just 1.

> What's your vision/plan for "Pay Group" area?

There will be two different ways of paying the group. For the prototype we will implement only one. It will have a list of users that need to be paid and how much to pay them. In this first mode, payments will be direct, user-to-user.

> ATM a group only has "threshold" settings. In the future, will be possible to to also change name / description or even arrange "widgets" order?

The dashboard will always have a top section that is fixed with primary widgets that cannot be re-arranged.

It may also have a bottom section where custom widgets can be placed and re-arranged by users.

> Only the group admin can do it, correctly? If so, should we also have an area to manage the member "roles"?

For the prototype the dashboard will be fixed and there won't be a way to customize it, but we will implement it in a way where it will be easy to make it customizeable in the future.

Members will have roles, yes, and that may actually be part of the prototype. These roles will likely be self-assigned, but in the future there may be roles that get voted on and/or be assigned by the admin.

> Is anything for the Prototype that we didn't started to develop yet? Something that is completely out of the UI, like removing a member for a group?

There are lots of thing that we haven't started to develop yet. The biggest part is the payments infrastructure. Other than that the rest of the features should be easier to add once our proposals system is revamped and improved by @hubudibu.

**Comment by sandrina-p** [comment]
As I said on Slack, the mockups for these task will be at Zeplin, and I invited @taoeffect and @hubudibu to see and comment.  Here's the [Web URL](zpl.io/aN08AM4) and  App URL:
```
zpl://project?pid=5b3dbc2551fc18af1295e6e2.
```

For those who aren't invited, here's the [public share version](https://scene.zeplin.io/project/5b3dbc2551fc18af1295e6e2) with preview only. - it doesn't show the sections / descriptions / comments.

**Comment by dotmacro** [comment]
@sandrina-p the public share link doesn't seem to work because Zeplin just gives me a "You’re not invited to this project" error message.

**Comment by sandrina-p** [comment]
@dotmacro Ups, wrong `copy paste`, link fixed! [public version](https://scene.zeplin.io/project/5b3dbc2551fc18af1295e6e2).

**Comment by taoeffect** [comment]
Closed in #436
