### ISSUE TITLE
GIMessage hashes are insecure and non deterministic

### ISSUE THREAD

**Issue by SGrondin** [okTurtles/group-income#479]
### Problem

I found 2 problems with message hasing while doing a quick review of the crypto code.

#### Hashes are insecure.

[Using `Math.random()`](https://github.com/okTurtles/group-income-simple/blob/8ca2ffb03a48203a32e4326963cac4f9624df91b/shared/GIMessage.js#L31-L32) is *NOT SAFE*, as explained [here](https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d). It's good enough for most little side projects, but it's not good enough when people's money is involved.

#### Hashes are non deterministic.

At the moment, the [hashing function](https://github.com/okTurtles/group-income-simple/blob/8ca2ffb03a48203a32e4326963cac4f9624df91b/shared/functions.js#L44-L51) is executed on a string generated by `JSON.stringify()`. `JSON.stringify()`, the way it is used [here](https://github.com/okTurtles/group-income-simple/blob/8ca2ffb03a48203a32e4326963cac4f9624df91b/shared/GIMessage.js#L39-L42) is *NON DETERMINISTIC* because the keys in an Object can be returned in any order in the string.

In other words, stringifying this object `{ "a": 1, "b": 2 }` will *sometimes* return `"{\"a\":1,\"b\":2}"` and *sometimes* return `"{\"b\":2,\"a\":1}"` depending on how it was created.

Thankfully both issues are easy to fix.

#### Hashes are insecure.

Use `uuid.v4()`. It goes to great lengths to ensure a safe source of entropy.

> Also, uuid.v4 isn’t needed, it’s a dependency we don’t want or need, and internally I doubt it’s using anything other than the built in random function

[False, here's the source](https://github.com/kelektiv/node-uuid/blob/master/lib/rng-browser.js)

Additionally, a quick `npm list | wc -l` tells me this project is already using 2795 dependencies. Ctrl-F `uuid` in the file `package-lock.json` and you'll see that `uuid` is *already* a dependency of group-income-simple.

#### Hashes are non deterministic.

`JSON.stringify()` takes more than one argument. All we have to do is:

`JSON.stringify(obj, Object.keys(obj).sort())` and now the keys are sorted in the output and the string is deterministic unless `obj` is a nested object, which doesn't seem to be the case here.

**Comment by taoeffect** [comment]
> Using Math.random() is NOT SAFE, as explained here.

This isn't a problem as our security does not depend on it, but on the crypto stuff that *hasn't been added yet.* It's only used because without it the same data will generate the same message.

Adding uuid isn't necessary, even if it is already a dependency of something, because we are continually removing dependencies. Any new dependency must be justified as *necessary*, and uuid in this case isn't.

> the way it is used here is NON DETERMINISTIC because the keys in an Object can be returned in any order in the string.

This also isn't a problem. I went through the same thing. I thought it was an issue and ended up realizing it wasn't.

Please see [this massive pull request](https://github.com/okTurtles/group-income-simple/pull/431) to see what I went through upon realizing that it doesn't matter that the keys aren't sorted deterministically.

To re-open this issue, you'll need to show *a real problem exists*, and so far I do not see one.
