### ISSUE TITLE
Implement the "3 questions" during onboarding

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#483]
### Problem

We're missing information that the distribution algorithm needs.

### Solution

- During user registration or onboarding, ask the questions outlined below
- If not during registration, then make sure there's a banner at the top of the dashboard nagging them to answer these questions
  - If such a banner exists, then make sure the UI also makes it clear that their "account has limited functionality" until they answer the questions

The first question is something along the lines of:

> Is your monthly income more or less than the mincome of {Currency}{Amount}?
> 
> o More
> o Less

Depending on which radio button they select, a different question appears below that one.

If they select "More", then they're asked:

> Up to how much do you pledge to contribute to the group each month? (You can change this in your contribution settings)

If they select "Less", then they're asked:

> What is your monthly income?

**Comment by sandrina-p** [comment]
Cool thing! Also following our discussion at https://github.com/okTurtles/group-income-simple/pull/482#discussion_r216517696, let me ask:

- Should these 3 questions be made on user onboarding or only when a user joins a group?
  - If it's on onboarding, how does the system knows the `{Currency}{Amount}`?

- When the user joins multiple groups, will we ask the same 3 questions for each group?

The way I see, these 3 questions should be displayed on the Contribution page, since they are directly related to the monetary contributions, both receiving and giving.

![image](https://user-images.githubusercontent.com/14869087/45360410-70c6db80-b5c7-11e8-8fca-1d1f62f11242.png)

Note that here you are assuming that doesn't make sense the user can "give" and "receive" at the same time. (although IMO in real life sometimes that can happen - imagine a freelancer job). 

So assuming the user can't have a giving and receiving monetary method enabled at the same time:

- If the user does "more", the receiving monetary box doesn't make sense as it is.
- If the uses does "less", the giving monetary box is the one that doesn't make much sense.

We are facing a situation where the UI related to monetary contributions doesn't reflect correctly the User journey. This should be improved.

What if... Instead of having a "giving / receiving" information oriented (2 columns), we display this information by using 2 sections "No monetary" and "Monetary"?
With that approach we are able to ask the user for "Monetary contributions" under a toggle (or radio inputs as you suggested) without having a confusing UI (the current monetary boxes). The non-monetary contributions part would remain as it is ("giving / receiving" 2 columns)

What do you think @taoeffect? I did my best to explain this without any draw... I plan to work on that part later today/tomorrow.

**Comment by taoeffect** [comment]
> Should these 3 questions be made on user onboarding or only when a user joins a group?
> If it's on onboarding, how does the system knows the {Currency}{Amount}?

Well, it definitely cannot be when they signup, so it could be on the invite screen, or it could be another screen after they join the group.

I actually do not know which would be better, this is something a UX expert would know better than me, so for now I'll just delegate to you to pick whatever you think provides better UI/UX.

> When the user joins multiple groups, will we ask the same 3 questions for each group?

That's a brilliant question, and possibly informs the direction you take on this.

- Clearly, if they make less than the mincome, then their answer about how much they make per month should be the same across all groups and not change, and so it should be a global attribute to their profile across all groups. **EDIT: Oops, the mincome can be different for different groups, so yes we should probably ask these questions for all groups**
- But if they make more than the mincome, then the amount they're willing to contribute to any particular group can change. In technical terms, this means the place this information is stored can also be in their global profile (not their group profile), but it can be in an object that is keyed by the groups they're in (so each key is the hash of a different group contract they're in, and each value is the respective amount they're willing to pledge to that group each month). That way the answers to both questions would be stored in the same place (the global profile). This technical detail isn't something you need to worry about, but I'm just sharing it with you to document this for myself for the future, and to give you a better understanding of how this would be implemented internally

> Note that here you are assuming that doesn't make sense the user can "give" and "receive" at the same time. (although IMO in real life sometimes that can happen - imagine a freelancer job).

It is true that if they're receiving mincome from the group, it doesn't make sense for them to be giving any... however, I think we should still have two columns as giving and receiving, because this lets us show what they're actually receiving and giving from the group, whether it's monetary or non-monetary, and the focus should be on that reciprocity relationship they have with the group.

Sorry I missed you earlier this morning! Let's coordinate on Slack and schedule a time to chat!

**Comment by sandrina-p** [comment]
This is solved by #480, right @taoeffect ?

**Comment by taoeffect** [comment]
Yep!
