### ISSUE TITLE
Display user's stated income prominently on Dashboard

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#501]
### Problem

Users might "forget" to update their stated income, thus leading to inaccurate distribution. We need to make sure they always remember to update it if their financial situation changes.

### Solution

Design a box to prominently display the user's claimed income (or in the case of a pledge, what their current pledge is) to remind users to keep their income info accurate and up-to-date, and make it simply for them to update it directly from the dashboard.

This issue should be assigned to Margarida once I get her GitHub account.

**Comment by mmbotelho** [comment]
This issue has been solved, from a UX/UI perspective, on the [new Dashboard mockups](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=1204%3A0). 

The solution was not exactly the same as suggested here: instead of the users stated income, we decided to show the users pledge (or the amount the user needs to receive) more prominently, solving the underlying issue here - a users financial situation can change from one month to the next :) .
