### ISSUE TITLE
Save all console messages to a log and create a page in the settings where it can be viewed

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#595]
### Problem

Sometimes `console.log/debug/warn` messages put extremely important debugging information into the console that can be critical for recovering from errors. Asking users to open up the dev tools to troubleshoot a problem is a no-go.

### Solution

- We need to make it simple for users to send us the output of the console log, and also simple to adjust what information gets placed there while being careful not to log things like passwords or private keys
- We need to create a page in the UI itself to display this information
- This log needs to be persisted and save information from `.warn` and `.error` messages, because they might log important information necessary for recovery

NOTE: this issue is about the same as #353...

**Comment by dotmacro** [comment]
Note: This issue is related to #353

**Comment by sandrina-p** [comment]
@taoeffect should we do this for the prototype? I think so... maybe I can explore solutions for this.

You say the log should be persisted. Maybe for the prototype, a simple solution is to save it on localStorage, without the need/cost to save it on the server. What do you think?

**Comment by taoeffect** [comment]
> @taoeffect should we do this for the prototype? I think so... maybe I can explore solutions for this.

Yes, this page definitely needs to be created for the prototype. A simple design is needed first from either you or @mmbotelho (or both, i.e. feel free to create one using basic components as you see fit and then make adjusts per @mmbotelho's designs).

It should also be related / tied-to the recovery page (#761) somehow. I.e. links to both of them should be found in the same section of the app, and each should link to the other.

> You say the log should be persisted. Maybe for the prototype, a simple solution is to save it on localStorage, without the need/cost to save it on the server. What do you think?

Yes, localStorage definitely, logs are never sent to the server.

**Comment by sandrina-p** [comment]
Okay, I addressed this issue to me and @mmbotelho. While I wait for her work on this I'll research the technical side of it.

**Comment by mmbotelho** [comment]
@sandrina-p can you help me understand this better? I have a few questions:

1. What do these messages look like? Can you give me some examples?
2. Can you give me some examples of when these might happen? 
3. What can users do with this information? (maybe @taoeffect can answer this one) Open a Github issue? Contact us? Do nothing at all unless we ask them to send them our way?  

Thank you!

**Comment by sandrina-p** [comment]
@mmbotelho

1. these messages can be anything thrown by Javascript while the application runs. You know, those very "geek" messages you usually see on the devtools console, [(example)](https://user-images.githubusercontent.com/14869087/74514149-ebee9880-4f03-11ea-8860-9adc9258947f.png). Our goal here is to do a more user-friendly version of that for non-geek people, so they can send that to us.

Usually, any message follows this format:
- Type (log, info, warning, error)
- Message - the main "body" of the message.
- Location - where the error happens (filename and line, etc..).
- Stack Trace - this is like the "path" of the error, where exactly it came from. This is where things can get nasty and very long. [example](https://user-images.githubusercontent.com/1939483/38484036-692c98d6-3bd5-11e8-9680-b40de995184d.png).

There are more things, if you feel brave, you can see directly the [Error API on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Error_instances) but I believe what I described is already enough.


React is a good example where they have a nice custom error handling page when something crashes while we are developing. [see example](https://user-images.githubusercontent.com/14869087/74514363-4c7dd580-4f04-11ea-9043-74796c769e81.png) Note how they "collapse" the error stack part.

2. Oh... these can happen when we less expect! (that's why we need this page after all ahahah). This is the page users will access when they receive any type of error ex: "Failed to Create a Group. [Click to troubleshoot.]" and they will be redirected to this page. (related issue https://github.com/okTurtles/group-income-simple/issues/788)

3. I would say to open a Github issue, but that's "too geeky". Something we could have is a "click to export" or "click to copy" button where they could send us the exported file.txt attached or paste the logs on Github or any other forum.

**Comment by mmbotelho** [comment]
Hmmm so this is a page that keeps track of all the errors (if there are more than one) that are happening OR that happened in the past?

And users can copy paste them and send them our way in case they need to?

**Comment by mmbotelho** [comment]
_Note to self:_ Examples of software that do this, so I can see how they work:
- https://raygun.com/platform/crash-reporting
- https://sentry.io/welcome/
- https://logrocket.com/

**Comment by sandrina-p** [comment]
> Hmmm so this is a page that keeps track of all the errors (if there are more than one) that are happening OR that happened in the past?

Yes, @mmbotelho. Errors that happened in the past, 1 sec ago or 1 week ago. Maybe we should split these errors by "session", this is, each time the user access the app, instead of by date. What do you think @taoeffect ?

> Note to self: Examples of software that do this, so I can see how they work:

Take in account that those software are experts and very very detailed on this type of work. In our case, we just want 1% of what they do, only the very essentials as I described before.

**Comment by mmbotelho** [comment]
> Take in account that those software are experts and very very detailed on this type of work. In our case, we just want 1% of what they do, only the very essentials as I described before.

👍

**Comment by mmbotelho** [comment]
I made a rough sketch of this page. I need your feedback on it, so I know if I'm moving in the right direction with this.

### Use case
_What is the goal of this page?_

There's something off about the app, user notices it and contacts us. Our team requests that they send their logs our way, so we can look into it.

### Content
_What information needs to be on this page?_

- Log type
    - Error;
    - Warning;
    - Info;
- Error description;
- More information on each error (collapsible);
- Filter errors by type;
- Download file (so they can send it to us if necessary);

[Here's the figma screen for this](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=9765%3A48). Let me know what you think!

**Comment by taoeffect** [comment]
@mmbotelho Left a comment on Figma! The download button is OK, the ability to filter is OK, but the log itself should just be a simple unstyled `<textarea>`.
