### ISSUE TITLE
Fix links style

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#642]
### Problem

![Aug-29-2019 12-25-23](https://user-images.githubusercontent.com/14869087/63936646-3a909f00-ca58-11e9-9036-53fe670ecd41.gif)

The current link style is done with a custom border to simulate a "fancy underline". Because of its nature, the style breaks when the link has two lines.

### Solution

@mmbotelho I noticed that on Figma we use a default underline. Which behavior is the correct here?

cc @pieer @taoeffect

**Comment by mmbotelho** [comment]
I used a border on Figma as well. What do you mean by the "style breaks"? It's not clear from the GIF @sandrina-p

**Comment by sandrina-p** [comment]
When we hover/focus a link, the underline effect disappears... and it shouldn't

**Comment by mmbotelho** [comment]
Ahhh I see... It doesn't show the animation, right?

Well, if it makes things inconsistent, I would say that we can keep it simple and remove the animation. If we do this, then what your gif shows should be the expected behavior in all links (including the blue ones).

What do you think @pieer @taoeffect @sandrina-p ?

**Comment by sandrina-p** [comment]
For me it's fine. Maybe @pieer has another suggestion

**Comment by taoeffect** [comment]
Sorry @sandrina-p I'm not following, what do you mean by "it's fine", that this issue should be closed, or something else?

I'm fixated on the fact that the text reads "supermajority 175", that's the real issue here 😆 .

As far as links go, personally I like it when links are simple, without fancy animations, but do have some kind of simple `:hover` effect. That's just my opinion of course, and I'll defer to @mmbotelho's judgement here.

**Comment by mmbotelho** [comment]
I agree @taoeffect. If it keeps things more manageable then I'm 100% for removing the animation.

**Comment by sandrina-p** [comment]
Ups @taoeffect. What I want to say it's I agree with the suggestion of removing the current link animation and keep it with the simple default underline.

**Comment by mmbotelho** [comment]
@sandrina-p let's not use text-underline. Let's keep using border, please - text underline can have some weird visual effects

**Comment by sandrina-p** [comment]
Ah okay, then, border without animations, it's fine as well. @pieer what do you think?

**Comment by pieer** [comment]
Remove the fancy link animation.
