### ISSUE TITLE
After joining a group, members list sometimes only shows 1 member

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#648]
### Problem

While testing #636, I noticed that the members list showed only 1 member in the group after joining it, when there should be 2:

![Screen Shot 2019-08-30 at 10 20 32 PM](https://user-images.githubusercontent.com/138706/64058128-7f115d00-cb74-11e9-99f6-57f373f6bcf2.jpg)

Notice it even says "2 members".

This happens in the container tab for the user who *joined the group* (not the container that that invited this user -- in that tab it shows both users).

### Solution

Fix.

**Related:** #647

**Comment by mmbotelho** [comment]
The correct behaviour is to only show one member - because the other member is the user who is viewing this page, who is not listed here (that is the correct behaviour).

Now, I see a different problem here - the link with the "show all x members" should not be displayed unless the group has more than 10 members. This link should also subtract 1 member (the user who is using the app). 

cc @sandrina-p

**Comment by taoeffect** [comment]
> This link should also subtract 1 member (the user who is using the app).

Nein. Your name should appear in both this list and the "all 2 members" list, just as it does in every other app.

**Comment by mmbotelho** [comment]
@taoeffect this was not originally in the designs (meaning that @sandrina-p's implementation was correct). I will add this to my to-do list:
- Add the user themselves to the members list;
- Figure out which actions should be available. The only logical action I see atm is "Edit profile";

**Comment by mmbotelho** [comment]
Fixed on the [design system](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=48%3A70) and [dashboard](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=1204%3A0) mockups (Figma).

cc @sandrina-p @taoeffect

**Comment by sandrina-p** [comment]
I looked into this and couldn't find the solution for it, but so far this is what I know:
- The member creator is the only member who sees the list correctly.
- The list is incorrect for all the other members (where it's missing the member creator).
- The text "All [X] members" is always correct because its information is based on the `state[currentGroupId].profiles` length - which contains only each member hash.
- When we iterate the members list, it goes to the Store and look for the members by the hash This is where the bug happens: **The info about the member who created the group isn't saved on the store.** What's why it's not displayed in the list, because there isn't any information about it.

@taoeffect, so my question is: How it works the profiles in the store at the moment? How does a user knows what contracts should he subscribe to and where are all of these contracts saved? I looked for a bunch of files but I still struggle to understand what's going on...

**Comment by taoeffect** [comment]
> @taoeffect, so my question is: How it works the profiles in the store at the moment? How does a user knows what contracts should he subscribe to and where are all of these contracts saved? I looked for a bunch of files but I still struggle to understand what's going on...

All of this is done in `group.js`

**Comment by sandrina-p** [comment]
Well... @taoeffect that answer didn't help me much... I looked at that file but didn't understand how it works exactly. I need you to explain things in more detail. 

So, this bug seems easy to fix, so maybe we could do pair programming to debug and fix it during our call tomorrow, what do you think?

**Comment by taoeffect** [comment]
> So, this bug seems easy to fix, so maybe we could do pair programming to debug and fix it during our call tomorrow, what do you think?

That sounds good 👍
