### ISSUE TITLE
Explore Tailwind CSS

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#769]
### Problem

Not really a problem which is why I'm marking this "Low Priority", but purely research as to whether our CSS setup can benefit from [Tailwind CSS](https://tailwindcss.com/), which looks cool

### Solution

Research:

- https://tailwindcss.com/
- https://markus.oberlehner.net/blog/setting-up-tailwind-css-with-vue/

**Comment by sandrina-p** [comment]
Hum... We jumped out of Bulma to decrease dependencies a not-used CSS. Now we have a cleaner CSS. I don't see the benefits of re-adding a CSS framework.

**Comment by taoeffect** [comment]
That's a very good point. I definitely want to avoid adding dependencies. Perhaps there's still something interesting/useful from this project that we can adopt or implement ourselves? Really I wouldn't know, you're the frontend dev / CSS expert, not me! :)

**Comment by sandrina-p** [comment]
Well, I know the framework. It follows the CSS atomic approach, and I'm not a big fan of it, mainly because of how dirty it turns the HTML (full of CSS classes) and how fragmented the styling works. Which is kinda the opposite of our current strategy, component-oriented. Maybe @pieer has something to say about it.

**Comment by taoeffect** [comment]
> It follows the CSS atomic approach, and I'm not a big fan of it, mainly because of how dirty it turns the HTML (full of CSS classes) and how fragmented the styling works.

I think that's persuasive enough of a point for me to close this issue :)
