### ISSUE TITLE
State structure improvements

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#804]
### Problem

This project started with a simple file structure, right for its needs. 
- A folder `views/` with Vue components, each one on its own file.
- A folder `model/contracts` with contracts, each one on its own file.
- A single file `model/state.js` with all the Vuex state management inside.

Now that we are close to finishing all the core features for the prototype, `state.js` is getting too big. One of the struggles is readability and naming inconsistencies/conflicts/purpose as new getters appear. (ex: `ourIdentityContractId` vs `ourUserIdentityContract` or `groupProfile` vs `groupProfiles`)

### Solution

Discuss the next step to evolve this structure and how it co-exists with `sbp`.

Here are some references about this.
- [Vuex - modules](https://vuex.vuejs.org/guide/modules.html)
- [Article - Large-scale Vuex applications structures](https://medium.com/3yourmind/large-scale-vuex-application-structures-651e44863e2f)

So, what's your vision for the next step?

cc @taoeffect and @pieer

**Comment by pieer** [comment]
I believe that:
- sbp event registration and handleEvent functions could be move into a different file. Maybe model/utility/eventHandler.js
- Move model/errors.js to model/utility/error.js
- Move model/database.js to model/utility/database.js
- Remove model/constants.js

- In this file model/state.js we should have only mutations, getters and actions left.

Then I guess it's a good idea to split the state in 3 files: settings / user / group

So my recommendation:
model/state/user.js
model/state/group.js
model/state/settings.js
model/state/colors.js
model/utility/error.js
model/utility/database.js
model/utility/eventHandler.js

**Comment by taoeffect** [comment]
Some thoughts:

I like the introduction of `controller/actions` that #801 introduces, and think this can help move some of the Vuex actions out of state.js. For example, `syncContractWithServer`, `login`, and `logout` can be migrated to SBP controller actions. This is in line with the TODO that's been in the state.js source for quite some time:

```
// TODO: convert all these to SBP... and/or call dispatch through SBP only!
```

Doing this leaves only one Vuex action, `handleEvent`, and I think that that action and everything related to it can be moved into its own file under either `model/` or `controller/`, but probably `model/` makes more sense since it's integral to the building of the Vuex state in the app.

Then it can be registered under SBP instead of as a Vuex action, since that gives us SBP benefits like logging, and less dependence on third-party libraries. We'll then be able to remove the `'state/vuex/dispatch'` selector since all actions will have been registered as SBP selectors and can be called directly through SBP.

Regarding:

> model/state/user.js
> model/state/group.js
> model/state/settings.js
> model/state/colors.js
> model/utility/error.js
> model/utility/database.js
> model/utility/eventHandler.js

My concern here is that `model` already means the same thing as `state`, so having `model/state` might be a bit redundant? Re `model/state/user.js` and `model/state/group.js`, are those for the respective getters? Splitting them up like that might make sense, or it might be OK for now to just have them all under `model/getters.js`.

However, regarding the getters, there is an open issue assigned to me that needs to be addressed: #749 — this relates to the relationship between the global Vuex getters, and the "smart contract" code that currently sometimes makes use of them through the hackish `'state/groupContractSafeGetters'` (required for safety).

So, because of the complexities surrounding #749, I think maybe we should put this issue on hold, until that issue is closed (which should be happening as soon as I get back to coding after my work on blog posts and newsletters is done).

**Comment by sandrina-p** [comment]
I agree with splitting getters in modules as @pieer suggested (user, group, settings). That way it follows the same convention as the contracts and the new actions (from #801). 

So, it seems we all know more or less what's the next step (modules), so it's a matter of time to get it done when the time comes.

**Comment by taoeffect** [comment]
Note a PR I just submitted, #842, has started moving getters into contract definition files! 😄
