### ISSUE TITLE
Add finishing touches to GroupMembers.vue

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#827]
### Problem

<img width="1181" alt="Screen Shot 2020-02-08 at 3 13 14 PM" src="https://user-images.githubusercontent.com/138706/74093404-490ec800-4a86-11ea-8129-fd6d774f7692.png">

The screenshot above shows what the group members list currently looks like with 13 members. Note that some things are missing from the Figma design:

- `displayName` isn't shown for users, only `username`
- The user that's you doesn't have `(you)` next to their name
- New users do not have the `new` tag next to their name (and it's also not clear to me whether they should be at the top or not, that's something @mmbotelho can comment on)

### Solution

Address each of these issues in turn, either as multiple PRs or one big PR.

**Comment by sandrina-p** [comment]
I can fix these bugs. @mmbotelho can you clarify when the "new" tag should disappear?

**Comment by mmbotelho** [comment]
Sure @sandrina-p ! 

Let's say Jane, Anne and Mary have a group. Carl is added to the group. Anne accesses the app the day after Carl joined. The "new" tag is there and will remain there for 24 hours. 

Mary visits the app 2 months later for the first time since Carl joined. The new tag is there, and will remain there for 24 hours.

**Comment by sandrina-p** [comment]
@mmbotelho thanks for the explanation, it makes sense! I'll address it on a future PR :)

**Comment by sandrina-p** [comment]
@mmbotelho, now that I'm implementing the "new" tag logic, it's way more complex than I initially thought. I agree that your solution is the best UX, but the development effort is too high. I could explain why, but to save you from bored words, let's skip that part (I can still explain if you want to). So, could you simplify the logic for the prototype?

I suggest to show the "new" tag only during 48h after the member joins the group. If a user logs in only one week later the tag won't be visible. In other words, the tag only depends on when the member joined the group, not when a user visits the group.

What do you think?

---- 

I have another question: If I join a recent group with 4 members, does it make sense to show the "NEW" tag next to the other members that joined before me? I don't think so... because, as a new member, everything about the group is "new"... In other words: We should only show the "NEW" tag on members that join after us.

**Comment by mmbotelho** [comment]
@sandrina-p ok! We can make it work like this:
- All members that joined before me don't have a "new" pill;
- The "new" pill is visible for a certain amount of time. Now, I'm not sure if 48hours is the best window, because ideally, most users will only visit the website once a month, to check their monthly contributions. Let's maybe bump it up to a week?

**Comment by sandrina-p** [comment]
@mmbotelho 
- Okay
- Yes, one week is fine! Working on it
