### ISSUE TITLE
Remove $spacer to simpler rem values

### ISSUE THREAD

**Issue by pieer** [okTurtles/group-income#859]
### Problem

There is incistency with value sometime using $spacer sometime rem and the actual solution like $spacer*1.5 or $spacer-md - $spacer-xs or $spacer-mdxs are far from ideal.

### Solution

Replace all $spacer-md by 1rem etc... which is much simpler

**Comment by taoeffect** [comment]
I haven't read this article, but it just came across my screen, and am wondering whether you or @sandrina-p think it makes any valid points? https://vasilis.nl/nerd/dislike-rem-unit/

**Comment by sandrina-p** [comment]
@taoeffect that article is from 2013 and many of the points mentioned are not valid anymore. All modern browsers support `rem`, even IE9 and Opera Mini. The bugs mentioned don't happen anymore and OP is mixing `rem` and `em`. They are two different things and we only use `rem`.

IMO using `rem` doesn't have any downside nowadays. The only tricky part is the x/16 conversion from pixels, but even that is okay because our spacers are multiples of 8, so we write pretty `rem` values (1, 1.5, 2, 2.5, etc...).
