### ISSUE TITLE
Design/Implement Clear Proposals button

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#924]
### Problem

Currently we don't have a good way of clearing closed/passed/expired proposals from the proposals section.

### Solution

In addition to having the ability to manually clear passed proposals by clicking a button (which moves them to the "All Proposals" modal, which needs to be implemented), there can be automatic ways, e.g.:

- Proposals can be automatically removed from the proposals section after a number of days
- After an invite link is used
- Other ideas?

This issue is related to: #925 — Implement archiving of proposals

**Comment by dotmacro** [comment]
My understanding was that closed proposals would automatically be moved to the "All proposals", just like sent payments are automatically moved from "todo" to the "sent" tab. (Not based on any discussion--just what seemed to make sense based on internal consistency.)

> In addition to having the ability to manually clear passed proposals by clicking a button

It seems unnecessary to have users manually clear closed proposals (whether passed or failed) because they are notified of what's going on. The user receives an notification when the proposal is available, shortly before the proposal closes, and when the proposal has closed (notifying them of the results). 

For internal consistency, automatically moving proposals would match the behavior of payments. 

Would it help to rename "All Proposals" to "Closed proposals"?

**Comment by taoeffect** [comment]
There are still a few issues though (which are more or less related to the same overall issue):

1. Users who made the proposals need to still see them in the proposals section once they pass, so that they can visually be aware of any invite links. It's not enough to simply show a notification somewhere. We need to keep "object persistence" of proposals present so that they don't get confused, e.g. "Where did my proposal go? What happened to it?"
2. Users who voted in proposals might also want to know what happened to them.
3. Even if we immediately archive them, we still need to address these issues, and the designs haven't yet done a clear/good job of that (there's a "TBD" note about it on Figma). I.e. users must be informed about the result of the proposals in some other prominent part of the app, and preferably in multiple places at the same time, e.g. in the Notifications menu, and in the chat, etc. (This is really just a restatement of the other points)

So I feel that the proposals should stick around for a bit in the proposals section in some way. I do not consider it unnecessary.

EDIT: none of this means that we cannot automatically clear proposals in some way. Just that I think if we do that we should also make sure to leave them around in certain instances, and offer a manual way to clear them as well.

**Comment by dotmacro** [comment]
>     2. Users who voted in proposals might also want to know what happened to them.

If we decide to auto-archive proposals, I think the notifications and UI changes (e.g. members marked as new, mincome changes) are sufficient to address this.

>     3. (there's a "TBD" note about it on Figma). I.e. users must be informed about the result of the proposals in some other prominent part of the app, and preferably in multiple places at the same time, e.g. in the Notifications menu, and in the chat, etc. 

Ah, thanks! I'd missed that note. Notifications and chat seem sufficient. However, I really do like the current designs that show recently closed proposals in the default proposals view. Hmmm...

>     1. Users who made the proposals need to still see them ... so that they can visually be aware of any invite links. 

Ah, right. This is really important. It may be easier to keep proposals on the dashboard for a bit than to design a different way of showing this. Would the invite proposal still auto-archive for the proposer, or would it stay until manually cleared (like "not received" payments)?

**Comment by sandrina-p** [comment]
This reminds me of the "New" tag next to the members list. When it should be there and remove it when it's no longer necessary. Finding the sweet spot for "no longer necessary" is a tricky UX and technical challenge.

I see GI as an app where users go there periodically, (best case scenario would be just once a month to mark payments/see received payments). Removing the proposal once it's approved seems too harsh for me because users might forget about it or want to be reminded of the group history after they visit the dashboard after a while. I'd leave the proposal there with an "archive" button, like e-mails.

On the technical side, we can move the proposals to the database immediately after a final result (approval/reject/canceled), keeping in the Vuex store only its hash. Then we use that hash to fetch the proposal status from the database when needed. (a.k.a when the user visits the dashboard or when they visit the proposals archive)

**Comment by mmbotelho** [comment]
As I said on Slack, the simplest way to solve this would be to move proposals to the "closed proposals" page once they are closed. Let's not forget that there's a notification bell inside the app as well that will lead users there, even if they have push notifications disabled or if we don't have email notifications. 

The only case where users absolutely need to have the proposal in the Dashboard is for adding new members - and it should only remain there for the person who created the proposal, so they can see the invite link. In that case, we can leave the proposal there, with the invite link, until that link is used OR it expires, whatever happens first. 

Apps need to be smart and do as much as possible automatically - that is what technology is for. Having a button there to "dismiss" a payment seems too much like having a piece of paper that needs to be manually archived. The path to see all proposals (in case someone is looking for a proposal and can't find it) is clear and easy to understand. 

I think we are overthinking and over complicating something that can be simple. I'm not opposed to having a "dismiss/clear" button there, I just think it's unnecessary.

**Comment by sandrina-p** [comment]
I totally forgot about the notifications bell inside the app. Once we have that, I agree that there's no need to keep the proposals visible in the dashboard.

**Comment by taoeffect** [comment]
OK, let's go with that approach. :) 👍

**Comment by leihla** [comment]
Mention this issue back in #[Finish designs for new proposals look & create issue for implementation](https://github.com/okTurtles/group-income/issues/1288#)
 
For reference, Proposal Archival Process should work as follows:
- As discussed with @taoeffect, there is no need to have an "Archive Proposals" button as proposals should be archived automatically.
- Once everyone has voted on the proposal or when the expiration date is reached, the proposal voting process is finished and the proposal is either accepted or rejected.
- Once this happens, a notification should be sent to all users, notifying them of the voting result - the link should go directly to that proposal, either it is in the dashboard widget or "see all proposals" modal
- Closed proposals can be showed on the dashboard widget for 24 hours after the proposal has been voted on and then should be archived automatically
- The dashboard widget should only show active/open proposals or proposals closed within the last 24 hours.

**Comment by taoeffect** [comment]
OK, closing this issue.
