### ISSUE TITLE
Minimum income requirement is currently one-size-fits-all

### ISSUE THREAD

**Issue by john-light** [okTurtles/group-income#937]
### Problem

Group Income is currently structured as a "one-size-fits-all" deal e.g. in the screenshot below the group defines its minimum income as $1000 for everyone.

![gi1](https://user-images.githubusercontent.com/9424721/83571381-2b72dc00-a517-11ea-8af6-8109cd47ca3d.png)

### Solution

There could be an alternative way of doing group income: where every member of the group defines their own minimum income level, and the other members of the group decide if it's reasonable or not. For example, someone who lives in an expensive city or the expensive part of town is going to have different minimum income needs than someone who lives in a rural area or a less affluent part of town. The former individual may have a minimum income requirement of $1000, while the latter may only need half that. Group Income currently does not capture this dynamic.

**Comment by dotmacro** [comment]
[Scott](https://twitter.com/scottsantens) explains most of my thoughts on this more clearly than I can: [Should the Amount of Basic Income Vary With Cost of Living Differences?](http://www.scottsantens.com/should-the-amount-of-basic-income-vary-with-cost-of-living-differences)

Additionally, we don't want people in the mindset of "how much do I really actually _need_ to survive?" because any extra can help them better themselves, which benefits everyone. Any "extra" mincome can be used to better one's position, whether that's through purchasing supplies, paying for tuition or therapy, or moving to a more expensive area with better opportunities or a simpler commute. We want individuals to *thrive*, not just survive.

With the current iteration, users are also free to adjust their income details to change the amount they receive, or to send more/less than requested.

**Comment by john-light** [comment]
> With the current iteration, users are also free to adjust their income details to change the amount they receive, or to send more/less than requested.

This is an interesting wordaround! Thanks for that. And thanks for the other links, will take a look.

**Comment by taoeffect** [comment]
Safe to close? Let us know if you feel the above isn't adequate!
