### ISSUE TITLE
Change linter to still compile

### ISSUE THREAD

**Issue by sdegutis** [okTurtles/group-income#980]
### Problem

When writing code, if there are stylistic errors, the linter will refuse to compile changes. This interrupts the cognitive flow of the developer, by changing focus away from the bigger-picture change to minor details about code style. This has the potential to slow down development significantly.

### Solution

The linter should emit warnings by default, but still compile. During a CI phase, a flag could be passed to change these to errors that fail the CI tests. This ensures that we can still see whether the linter is satisfied by the time code gets to PRs, but allows developers more freedom to code naturally and flowingly, and fix up stylistic differences at a more convenient time.

**Comment by snowteamer** [comment]
I agree with this, especially since full linting can be slow on low-end hardware, which is not good either for the cognitive flow.

I suggested the use of ESLint's `--cache` option as a mitigation, but it would probably not play well with git branch switching during development, as the `.eslintcache` file would go out of sync with the working tree.

On the other hand, your suggestion to convert errors into warnings sound pretty safe, while still requiring a minimal amount of change.

However, I would prefer the warnings become actual errors during a pre-commit or pre-push hook rather than later in the CI tests, as @F1LT3R suggested.
